// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module Frontend(
  input          clock,
                 reset,
                 auto_icache_master_out_a_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output         auto_icache_master_out_a_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_icache_master_out_a_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_icache_master_out_d_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_icache_master_out_d_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_icache_master_out_d_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [511:0] auto_icache_master_out_d_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_icache_master_out_d_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 io_cpu_might_request,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_cpu_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [39:0]  io_cpu_req_bits_pc,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_cpu_req_bits_speculative,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_cpu_sfence_valid,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_cpu_sfence_bits_rs1,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_cpu_sfence_bits_rs2,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [38:0]  io_cpu_sfence_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_cpu_resp_ready,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  output         io_cpu_resp_valid,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_cpu_resp_bits_btb_taken,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_cpu_resp_bits_btb_bridx,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  output [4:0]   io_cpu_resp_bits_btb_entry,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  output [7:0]   io_cpu_resp_bits_btb_bht_history,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  output [39:0]  io_cpu_resp_bits_pc,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  output [31:0]  io_cpu_resp_bits_data,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  output         io_cpu_resp_bits_xcpt_pf_inst,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_cpu_resp_bits_xcpt_gf_inst,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_cpu_resp_bits_xcpt_ae_inst,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_cpu_resp_bits_replay,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_cpu_btb_update_valid,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [4:0]   io_cpu_btb_update_bits_prediction_entry,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [38:0]  io_cpu_btb_update_bits_pc,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_cpu_btb_update_bits_isValid,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [38:0]  io_cpu_btb_update_bits_br_pc,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [1:0]   io_cpu_btb_update_bits_cfiType,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_cpu_bht_update_valid,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [7:0]   io_cpu_bht_update_bits_prediction_history,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [38:0]  io_cpu_bht_update_bits_pc,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_cpu_bht_update_bits_branch,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_cpu_bht_update_bits_taken,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_cpu_bht_update_bits_mispredict,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_cpu_flush_icache,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  output         io_cpu_perf_acquire,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_cpu_perf_tlbMiss,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_cpu_progress,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_req_ready,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  output         io_ptw_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_req_bits_valid,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  output [26:0]  io_ptw_req_bits_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  output         io_ptw_req_bits_bits_need_gpa,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_resp_valid,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_ae_ptw,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_ae_final,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_pf,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_gf,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_hr,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_hw,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_hx,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [43:0]  io_ptw_resp_bits_pte_ppn,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_resp_bits_pte_d,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_pte_a,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_pte_g,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_pte_u,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_pte_x,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_pte_w,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_pte_r,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_resp_bits_pte_v,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [1:0]   io_ptw_resp_bits_level,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_resp_bits_homogeneous,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [3:0]   io_ptw_ptbr_mode,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_status_debug,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [1:0]   io_ptw_status_prv,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_0_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [1:0]   io_ptw_pmp_0_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_0_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_0_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_0_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [29:0]  io_ptw_pmp_0_addr,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [31:0]  io_ptw_pmp_0_mask,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_1_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [1:0]   io_ptw_pmp_1_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_1_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_1_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_1_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [29:0]  io_ptw_pmp_1_addr,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [31:0]  io_ptw_pmp_1_mask,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_2_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [1:0]   io_ptw_pmp_2_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_2_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_2_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_2_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [29:0]  io_ptw_pmp_2_addr,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [31:0]  io_ptw_pmp_2_mask,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_3_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [1:0]   io_ptw_pmp_3_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_3_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_3_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_3_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [29:0]  io_ptw_pmp_3_addr,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [31:0]  io_ptw_pmp_3_mask,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_4_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [1:0]   io_ptw_pmp_4_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_4_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_4_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_4_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [29:0]  io_ptw_pmp_4_addr,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [31:0]  io_ptw_pmp_4_mask,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_5_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [1:0]   io_ptw_pmp_5_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_5_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_5_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_5_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [29:0]  io_ptw_pmp_5_addr,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [31:0]  io_ptw_pmp_5_mask,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_6_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [1:0]   io_ptw_pmp_6_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_6_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_6_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_6_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [29:0]  io_ptw_pmp_6_addr,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [31:0]  io_ptw_pmp_6_mask,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_7_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [1:0]   io_ptw_pmp_7_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input          io_ptw_pmp_7_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_7_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
                 io_ptw_pmp_7_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [29:0]  io_ptw_pmp_7_addr,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [31:0]  io_ptw_pmp_7_mask,	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
  input  [63:0]  io_ptw_customCSRs_csrs_0_value	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
);

  wire        s2_redirect;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:141:32, :332:26, :333:20, :337:{31,45}]
  wire [38:0] predicted_npc;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:266:25, :326:19, :327:21]
  wire        updateBTB;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:266:25, :294:125, :295:21]
  wire [1:0]  _GEN;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:266:25, :270:40]
  wire [1:0]  after_idx;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:266:25, :268:19]
  wire        taken_taken;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:251:71]
  wire [38:0] _io_cpu_npc_T;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:182:28]
  wire        _fq_io_enq_valid_T_6;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:180:52]
  wire        _btb_io_resp_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:194:21]
  wire        _btb_io_resp_bits_taken;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:194:21]
  wire        _btb_io_resp_bits_bridx;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:194:21]
  wire [38:0] _btb_io_resp_bits_target;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:194:21]
  wire [4:0]  _btb_io_resp_bits_entry;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:194:21]
  wire [7:0]  _btb_io_resp_bits_bht_history;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:194:21]
  wire        _btb_io_resp_bits_bht_value;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:194:21]
  wire        _btb_io_ras_head_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:194:21]
  wire [38:0] _btb_io_ras_head_bits;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:194:21]
  wire        _tlb_io_resp_miss;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19]
  wire [31:0] _tlb_io_resp_paddr;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19]
  wire        _tlb_io_resp_pf_inst;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19]
  wire        _tlb_io_resp_ae_inst;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19]
  wire        _tlb_io_resp_cacheable;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19]
  wire        _tlb_io_ptw_req_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19]
  wire        _fq_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:87:64]
  wire [4:0]  _fq_io_mask;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:87:64]
  wire        _icache_io_resp_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26]
  wire [31:0] _icache_io_resp_bits_data;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26]
  wire        _icache_io_resp_bits_ae;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26]
  reg         s1_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:103:21]
  reg         s2_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:104:25]
  wire        s0_valid = io_cpu_req_valid | ~(_fq_io_mask[2]) | ~(_fq_io_mask[3]) & (~s1_valid | ~s2_valid) | ~(_fq_io_mask[4]) & ~s1_valid & ~s2_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:87:64, :103:21, :104:25, :106:{5,16}, :107:{6,17,41,45,55,58}, :108:{6,17,41}, :109:35]
  reg  [39:0] s1_pc;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:111:18]
  reg         s1_speculative;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:112:27]
  reg  [39:0] s2_pc;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:113:22]
  reg         s2_btb_resp_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:114:44]
  reg         s2_btb_resp_bits_taken;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29]
  reg         s2_btb_resp_bits_bridx;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29]
  reg  [4:0]  s2_btb_resp_bits_entry;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29]
  reg  [7:0]  s2_btb_resp_bits_bht_history;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29]
  reg         taken_predict_taken;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29]
  wire        s2_btb_taken = s2_btb_resp_valid & s2_btb_resp_bits_taken;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:114:44, :115:29, :116:40]
  reg         s2_tlb_resp_miss;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24]
  reg         s2_tlb_resp_pf_inst;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24]
  reg         s2_tlb_resp_ae_inst;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24]
  reg         s2_tlb_resp_cacheable;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24]
  wire        _s2_xcpt_T = s2_tlb_resp_ae_inst | s2_tlb_resp_pf_inst;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24, :118:37]
  reg         s2_speculative;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:119:31]
  reg         s2_partial_insn_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:120:38]
  reg  [15:0] s2_partial_insn;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:121:28]
  reg         wrong_path;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:122:27]
  wire [39:0] _ntpc_T = {s1_pc[39:2], 2'h0} + 40'h4;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:111:18, :125:25, :153:97]
  wire        _taken_T_57 = _fq_io_enq_ready & _fq_io_enq_valid_T_6;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:87:64, :180:52, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg         s2_replay_REG;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:130:56]
  wire        s2_replay = s2_valid & ~_taken_T_57 | s2_replay_REG;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:104:25, :130:{26,29,46,56}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg  [1:0]  recent_progress_counter;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:151:40]
  wire        _io_cpu_perf_tlbMiss_T = io_ptw_req_ready & _tlb_io_ptw_req_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        s2_kill_speculative_tlb_refill = s2_speculative & ~(|recent_progress_counter);	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:119:31, :151:40, :152:49, :156:{55,58}]
  wire        _icache_io_s2_kill_T_2 = s2_speculative & ~(s2_tlb_resp_cacheable & ~(io_ptw_customCSRs_csrs_0_value[3])) | _s2_xcpt_T;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24, :118:37, :119:31, :175:{59,62}, :176:{39,42,71}, generators/rocket-chip/src/main/scala/tile/CustomCSRs.scala:46:69]
  reg         fq_io_enq_valid_REG;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:180:29]
  wire        _fq_io_enq_bits_replay_T_5 = s2_kill_speculative_tlb_refill & s2_tlb_resp_miss;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24, :156:55, :180:112]
  assign _fq_io_enq_valid_T_6 = fq_io_enq_valid_REG & s2_valid & (_icache_io_resp_valid | _fq_io_enq_bits_replay_T_5 | ~s2_tlb_resp_miss & _icache_io_s2_kill_T_2);	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :104:25, :117:24, :176:71, :180:{29,52,112,133,137,155}]
  assign _io_cpu_npc_T = io_cpu_req_valid ? io_cpu_req_bits_pc[39:1] : s2_replay ? s2_pc[39:1] : predicted_npc;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14, :113:22, :130:46, :131:16, :182:28, :266:25, :326:19, :327:21]
  wire [2:0]  _fq_io_enq_bits_mask_T_1 = 3'h3 << s2_pc[1];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:113:22, :185:50, generators/rocket-chip/src/main/scala/util/package.scala:155:13]
  wire        predicted_taken = _btb_io_resp_valid & _btb_io_resp_bits_taken;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:194:21, :209:29]
  wire [38:0] _GEN_0 = {s2_pc[38:2], 2'h0};	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:113:22, :153:97, :319:36, :320:33]
  wire        taken_prevRVI = s2_partial_insn_valid & (&(s2_partial_insn[1:0]));	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:120:38, :121:28, :229:{39,45}, :230:31]
  wire        taken_valid = _fq_io_enq_bits_mask_T_1[0] & ~taken_prevRVI;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:185:50, :230:31, :231:{38,44,47}]
  wire        taken_rviBranch = s2_partial_insn[6:0] == 7'h63;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:121:28, :235:{30,36}]
  wire        taken_rviJump = s2_partial_insn[6:0] == 7'h6F;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:121:28, :235:30, :236:34]
  wire        taken_rviJALR = s2_partial_insn[6:0] == 7'h67;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:121:28, :235:30, :237:34]
  wire        taken_rviReturn = taken_rviJALR & ~(s2_partial_insn[7]) & {_icache_io_resp_bits_data[3:2], _icache_io_resp_bits_data[0], s2_partial_insn[15]} == 4'h1;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :121:28, :237:34, :238:{34,42,46,66,77}]
  wire        taken_rviCall = (taken_rviJALR | taken_rviJump) & s2_partial_insn[7];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:121:28, :236:34, :237:34, :238:42, :239:{30,42}]
  wire [4:0]  _GEN_1 = {_icache_io_resp_bits_data[15:13], _icache_io_resp_bits_data[1:0]};	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :240:28]
  wire        taken_rvcBranch = _GEN_1 == 5'h19 | _GEN_1 == 5'h1D;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:240:{28,52,60}]
  wire        taken_rvcJump = _GEN_1 == 5'h15;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:240:28, :242:26]
  wire [5:0]  _GEN_2 = {_icache_io_resp_bits_data[15:12], _icache_io_resp_bits_data[1:0]};	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :240:28, :244:24]
  wire        taken_rvcJR = _GEN_2 == 6'h22 & ~(|(_icache_io_resp_bits_data[6:2]));	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :232:37, :244:{24,46,53,59}]
  wire        taken_rvcReturn = taken_rvcJR & {_icache_io_resp_bits_data[11:10], _icache_io_resp_bits_data[8:7]} == 4'h1;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :244:46, :245:{29,49}]
  wire        taken_rvcJALR = _GEN_2 == 6'h26 & ~(|(_icache_io_resp_bits_data[6:2]));	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :232:37, :244:{24,53,59}, :246:{26,49,62}]
  assign taken_taken = taken_prevRVI & (taken_rviJump | taken_rviJALR | taken_rviBranch & taken_predict_taken) | taken_valid & (taken_rvcJump | taken_rvcJALR | taken_rvcJR | taken_rvcBranch & taken_predict_taken);	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29, :230:31, :231:44, :235:36, :236:34, :237:34, :240:52, :242:26, :244:46, :246:49, :251:{17,40,53,71}, :252:{15,47,60}]
  wire        taken_predictReturn = _btb_io_ras_head_valid & (taken_prevRVI & taken_rviReturn | taken_valid & taken_rvcReturn);	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:194:21, :230:31, :231:44, :238:46, :245:29, :253:{49,61,74,83}]
  wire        taken_predictJump = taken_prevRVI & taken_rviJump | taken_valid & taken_rvcJump;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:230:31, :231:44, :236:34, :242:26, :254:{33,44,53}]
  wire        _taken_T_19 = taken_prevRVI & taken_rviBranch;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:230:31, :235:36, :255:53]
  wire        _taken_T_20 = taken_valid & taken_rvcBranch;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:231:44, :240:52, :255:75]
  wire        taken_predictBranch = taken_predict_taken & (_taken_T_19 | _taken_T_20);	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29, :255:{41,53,66,75}]
  wire        _taken_T_29 = s2_valid & s2_btb_resp_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:104:25, :114:44, :257:22]
  wire        _taken_T_5 = _taken_T_29 & ~s2_btb_resp_bits_bridx & taken_valid & (&(_icache_io_resp_bits_data[1:0]));	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :115:29, :229:{39,45}, :231:44, :232:37, :257:{22,69,88}]
  wire [32:0] _taken_npc_T_2 = taken_prevRVI ? {{13{_icache_io_resp_bits_data[15]}}, s2_partial_insn[3] ? {_icache_io_resp_bits_data[3:0], s2_partial_insn[15:12], _icache_io_resp_bits_data[4], _icache_io_resp_bits_data[14:5]} : {{8{_icache_io_resp_bits_data[15]}}, s2_partial_insn[7], _icache_io_resp_bits_data[14:9], s2_partial_insn[11:8]}, 1'h0} - 33'h2 : {{22{_icache_io_resp_bits_data[12]}}, _icache_io_resp_bits_data[14] ? {{3{_icache_io_resp_bits_data[12]}}, _icache_io_resp_bits_data[6:5], _icache_io_resp_bits_data[2], _icache_io_resp_bits_data[11:10], _icache_io_resp_bits_data[4:3]} : {_icache_io_resp_bits_data[8], _icache_io_resp_bits_data[10:9], _icache_io_resp_bits_data[6], _icache_io_resp_bits_data[7], _icache_io_resp_bits_data[2], _icache_io_resp_bits_data[11], _icache_io_resp_bits_data[5:3]}, 1'h0};	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :81:14, :101:19, :121:28, :194:21, :230:31, :232:37, :238:42, :243:{23,28}, :248:{23,31}, :285:{44,61}, generators/rocket-chip/src/main/scala/rocket/RVC.scala:44:{17,36,42,51,57,69,76}, :45:{27,35,43,49,59}, generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1134:44, :1136:65, :1138:39, :1140:62, :1142:57, :1148:8]
  wire [39:0] _taken_npc_T_3 = {s2_pc[39:2], 2'h0} + {{7{_taken_npc_T_2[32]}}, _taken_npc_T_2};	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:113:22, :153:97, :285:{39,44}]
  wire        taken_prevRVI_1 = taken_valid & (&(_icache_io_resp_bits_data[1:0]));	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :229:{39,45}, :230:31, :231:44, :232:37]
  wire        taken_valid_1 = _fq_io_enq_bits_mask_T_1[1] & ~taken_prevRVI_1;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:185:50, :230:31, :231:{38,44,47}]
  wire        taken_rviBranch_1 = _icache_io_resp_bits_data[6:0] == 7'h63;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :235:{30,36}]
  wire        taken_rviJump_1 = _icache_io_resp_bits_data[6:0] == 7'h6F;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :235:30, :236:34]
  wire        taken_rviJALR_1 = _icache_io_resp_bits_data[6:0] == 7'h67;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :235:30, :237:34]
  wire        taken_rviReturn_1 = taken_rviJALR_1 & ~(_icache_io_resp_bits_data[7]) & {_icache_io_resp_bits_data[19:18], _icache_io_resp_bits_data[16:15]} == 4'h1;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :237:34, :238:{34,42,46,66}]
  wire        taken_rviCall_1 = (taken_rviJALR_1 | taken_rviJump_1) & _icache_io_resp_bits_data[7];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :236:34, :237:34, :238:42, :239:{30,42}]
  wire [4:0]  _GEN_3 = {_icache_io_resp_bits_data[31:29], _icache_io_resp_bits_data[17:16]};	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :240:28]
  wire        taken_rvcBranch_1 = _GEN_3 == 5'h19 | _GEN_3 == 5'h1D;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:240:{28,52,60}]
  wire        taken_rvcJump_1 = _GEN_3 == 5'h15;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:240:28, :242:26]
  wire [5:0]  _GEN_4 = {_icache_io_resp_bits_data[31:28], _icache_io_resp_bits_data[17:16]};	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :240:28, :244:24]
  wire        taken_rvcJR_1 = _GEN_4 == 6'h22 & ~(|(_icache_io_resp_bits_data[22:18]));	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :232:37, :244:{24,46,53,59}]
  wire        taken_rvcReturn_1 = taken_rvcJR_1 & {_icache_io_resp_bits_data[27:26], _icache_io_resp_bits_data[24:23]} == 4'h1;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :244:46, :245:{29,49}]
  wire        taken_rvcJALR_1 = _GEN_4 == 6'h26 & ~(|(_icache_io_resp_bits_data[22:18]));	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :232:37, :244:{24,53,59}, :246:{26,49,62}]
  wire        taken_taken_1 = taken_prevRVI_1 & (taken_rviJump_1 | taken_rviJALR_1 | taken_rviBranch_1 & taken_predict_taken) | taken_valid_1 & (taken_rvcJump_1 | taken_rvcJALR_1 | taken_rvcJR_1 | taken_rvcBranch_1 & taken_predict_taken);	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29, :230:31, :231:44, :235:36, :236:34, :237:34, :240:52, :242:26, :244:46, :246:49, :251:{17,40,53,71}, :252:{15,47,60}]
  wire        taken_predictReturn_1 = _btb_io_ras_head_valid & (taken_prevRVI_1 & taken_rviReturn_1 | taken_valid_1 & taken_rvcReturn_1);	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:194:21, :230:31, :231:44, :238:46, :245:29, :253:{49,61,74,83}]
  wire        taken_predictJump_1 = taken_prevRVI_1 & taken_rviJump_1 | taken_valid_1 & taken_rvcJump_1;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:230:31, :231:44, :236:34, :242:26, :254:{33,44,53}]
  wire        _taken_T_48 = taken_prevRVI_1 & taken_rviBranch_1;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:230:31, :235:36, :255:53]
  wire        _taken_T_49 = taken_valid_1 & taken_rvcBranch_1;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:231:44, :240:52, :255:75]
  wire        taken_predictBranch_1 = taken_predict_taken & (_taken_T_48 | _taken_T_49);	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29, :255:{41,53,66,75}]
  wire        _taken_T_34 = _taken_T_29 & s2_btb_resp_bits_bridx & taken_valid_1 & (&(_icache_io_resp_bits_data[17:16]));	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :115:29, :229:{39,45}, :231:44, :232:37, :257:{22,88}]
  assign after_idx = taken_taken ? 2'h1 : 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:163:24, :251:71, :266:25, :268:19]
  assign _GEN = taken_taken ? ((taken_prevRVI ? taken_rviReturn : taken_rvcReturn) ? 2'h3 : (taken_prevRVI ? taken_rviCall : taken_rvcJALR) ? 2'h2 : {1'h0, ~(taken_prevRVI ? taken_rviBranch : taken_rvcBranch)}) : (taken_prevRVI_1 ? taken_rviReturn_1 : taken_rvcReturn_1) ? 2'h3 : (taken_prevRVI_1 ? taken_rviCall_1 : taken_rvcJALR_1) ? 2'h2 : {1'h0, ~(taken_prevRVI_1 ? taken_rviBranch_1 : taken_rvcBranch_1)};	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :81:14, :89:25, :92:9, :101:19, :124:29, :163:24, :194:21, :230:31, :235:36, :238:46, :239:42, :240:52, :245:29, :246:49, :251:71, :266:25, :270:{40,46,50}, :271:{46,50}, :272:{46,50}]
  wire [30:0] _GEN_5 = taken_prevRVI_1 ? {{12{_icache_io_resp_bits_data[31]}}, _icache_io_resp_bits_data[3] ? {_icache_io_resp_bits_data[19:12], _icache_io_resp_bits_data[20], _icache_io_resp_bits_data[30:21]} : {{8{_icache_io_resp_bits_data[31]}}, _icache_io_resp_bits_data[7], _icache_io_resp_bits_data[30:25], _icache_io_resp_bits_data[11:8]}} : {{21{_icache_io_resp_bits_data[28]}}, _icache_io_resp_bits_data[30] ? {{3{_icache_io_resp_bits_data[28]}}, _icache_io_resp_bits_data[22:21], _icache_io_resp_bits_data[18], _icache_io_resp_bits_data[27:26], _icache_io_resp_bits_data[20:19]} : {_icache_io_resp_bits_data[24], _icache_io_resp_bits_data[26:25], _icache_io_resp_bits_data[22], _icache_io_resp_bits_data[23], _icache_io_resp_bits_data[18], _icache_io_resp_bits_data[27], _icache_io_resp_bits_data[21:19]}};	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :230:31, :232:37, :238:42, :243:{23,28}, :248:{23,31}, :286:71, generators/rocket-chip/src/main/scala/rocket/RVC.scala:44:{17,36,42,51,57,69,76}, :45:{27,35,43,49,59}, generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1134:44, :1136:65, :1138:39, :1140:62, :1142:57, :1148:8]
  wire [39:0] _taken_npc_T_10 = (taken_prevRVI_1 ? {s2_pc[39:2], 2'h2} - 40'h2 : {s2_pc[39:2], 2'h2}) + {{8{_GEN_5[30]}}, _GEN_5, 1'h0};	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :81:14, :101:19, :113:22, :163:24, :194:21, :230:31, :283:33, :286:{23,36,66,71}]
  assign updateBTB = ~taken_taken & ~s2_btb_resp_valid & (taken_predictBranch_1 & taken_predict_taken | taken_predictJump_1 | taken_predictReturn_1) | ~s2_btb_resp_valid & (taken_predictBranch & taken_predict_taken | taken_predictJump | taken_predictReturn);	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:114:44, :115:29, :251:71, :253:49, :254:44, :255:41, :266:{13,25}, :294:{15,34,52,106,125}, :295:21]
  wire        taken = taken_taken | taken_taken_1;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:251:71, :307:19]
  assign predicted_npc = ~taken_taken & ~s2_btb_taken & s2_valid & taken_predictReturn_1 | ~s2_btb_taken & s2_valid & taken_predictReturn ? {1'h0, _btb_io_ras_head_bits[38:1]} : ~taken_taken & ~s2_btb_taken & s2_valid & (taken_predictBranch_1 | taken_predictJump_1) ? _taken_npc_T_10[39:1] : ~s2_btb_taken & s2_valid & (taken_predictBranch | taken_predictJump) ? _taken_npc_T_3[39:1] : predicted_taken ? {_btb_io_resp_bits_target[38], _btb_io_resp_bits_target[38:1]} : _ntpc_T[39:1];	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :81:14, :101:19, :104:25, :116:40, :125:25, :126:34, :194:21, :209:{29,56}, :210:21, :221:29, :251:71, :253:49, :254:44, :255:41, :266:{13,25}, :275:{15,30}, :279:44, :280:20, :282:{44,61}, :285:39, :286:66, :287:27, :326:19, :327:21, generators/rocket-chip/src/main/scala/util/package.scala:124:{15,38}]
  wire        _GEN_6 = ~s2_btb_taken & taken;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:116:40, :187:22, :307:19, :332:{11,26}, :333:20, :334:34]
  assign s2_redirect = ~s2_btb_taken & taken & _taken_T_57 | io_cpu_req_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:116:40, :141:32, :307:19, :332:{11,26}, :333:20, :337:{31,45}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:92:9]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:92:9]
      if (~reset & ~(~(io_cpu_req_valid | io_cpu_sfence_valid | io_cpu_flush_icache | io_cpu_bht_update_valid | io_cpu_btb_update_valid) | io_cpu_might_request)) begin	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:92:{9,10,102,130}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:92:9]
          $error("Assertion failed\n    at Frontend.scala:92 assert(!(io.cpu.req.valid || io.cpu.sfence.valid || io.cpu.flush_icache || io.cpu.bht_update.valid || io.cpu.btb_update.valid) || io.cpu.might_request)\n");	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:92:9]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:92:9]
          $fatal;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:92:9]
      end
      if (~reset & s2_speculative & io_ptw_customCSRs_csrs_0_value[3] & ~_icache_io_s2_kill_T_2) begin	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:92:9, :119:31, :176:71, :190:{9,113}, generators/rocket-chip/src/main/scala/tile/CustomCSRs.scala:46:69]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:190:9]
          $error("Assertion failed\n    at Frontend.scala:190 assert(!(s2_speculative && io.ptw.customCSRs.asInstanceOf[RocketCustomCSRs].disableSpeculativeICacheRefill && !icache.io.s2_kill))\n");	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:190:9]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:190:9]
          $fatal;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:190:9]
      end
      if (~reset & ~(~s2_partial_insn_valid | _fq_io_enq_bits_mask_T_1[0])) begin	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:92:9, :120:38, :185:50, :231:38, :341:{11,12,35}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:341:11]
          $error("Assertion failed\n    at Frontend.scala:341 assert(!s2_partial_insn_valid || fq.io.enq.bits.mask(0))\n");	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:341:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:341:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:341:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _GEN_7 = s2_btb_taken ? _taken_T_5 | wrong_path : _taken_T_57 & taken_taken & ~taken_predictBranch & ~taken_predictJump & ~taken_predictReturn | _taken_T_5 | wrong_path;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:116:40, :122:27, :251:71, :253:49, :254:44, :255:41, :257:{88,97}, :262:20, :275:30, :276:{44,62,75,78,94}, :277:24, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _taken_T_61 = taken_valid_1 & ~taken_taken & (&(_icache_io_resp_bits_data[17:16]));	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :229:{39,45}, :231:44, :232:37, :251:71, :266:13, :302:37]
  always @(posedge clock) begin
    s1_valid <= s0_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:103:21, :109:35]
    s1_pc <= {_io_cpu_npc_T, 1'h0};	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :81:14, :101:19, :111:18, :182:28, :194:21, :377:33]
    if (io_cpu_req_valid)	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
      s1_speculative <= io_cpu_req_bits_speculative;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:112:27]
    else if (s2_replay)	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:130:46]
      s1_speculative <= s2_speculative;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:112:27, :119:31]
    else	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:130:46]
      s1_speculative <= s1_speculative | s2_valid & ~s2_speculative | predicted_taken;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:104:25, :112:27, :119:31, :137:{53,56,72}, :209:29]
    if (~s2_replay) begin	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:130:46]
      s2_btb_resp_valid <= _btb_io_resp_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:114:44, :194:21]
      s2_btb_resp_bits_taken <= _btb_io_resp_bits_taken;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29, :194:21]
      s2_btb_resp_bits_bridx <= _btb_io_resp_bits_bridx;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29, :194:21]
      s2_btb_resp_bits_entry <= _btb_io_resp_bits_entry;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29, :194:21]
      s2_btb_resp_bits_bht_history <= _btb_io_resp_bits_bht_history;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29, :194:21]
      taken_predict_taken <= _btb_io_resp_bits_bht_value;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29, :194:21]
      s2_tlb_resp_miss <= _tlb_io_resp_miss;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19, :117:24]
      s2_tlb_resp_pf_inst <= _tlb_io_resp_pf_inst;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19, :117:24]
      s2_tlb_resp_ae_inst <= _tlb_io_resp_ae_inst;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19, :117:24]
      s2_tlb_resp_cacheable <= _tlb_io_resp_cacheable;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19, :117:24]
    end
    if (_taken_T_57 & _taken_T_61)	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:121:28, :300:31, :302:{37,46}, :304:29, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      s2_partial_insn <= {_icache_io_resp_bits_data[31:18], 2'h3};	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :121:28, :124:29, :232:37, :304:37]
    fq_io_enq_valid_REG <= s1_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:103:21, :180:29]
    if (reset) begin
      s2_valid <= 1'h0;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :81:14, :101:19, :104:25, :194:21]
      s2_pc <= 40'h10000;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:113:22]
      s2_speculative <= 1'h0;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :81:14, :101:19, :119:31, :194:21]
      s2_partial_insn_valid <= 1'h0;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :81:14, :101:19, :120:38, :194:21]
      wrong_path <= 1'h0;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :81:14, :101:19, :122:27, :194:21]
      s2_replay_REG <= 1'h1;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:92:9, :130:56]
      recent_progress_counter <= 2'h3;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:124:29, :151:40]
    end
    else begin
      s2_valid <= ~s2_replay & ~s2_redirect;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:104:25, :130:46, :141:32, :142:12, :143:{9,21}, :144:{14,17}, :332:26, :333:20, :337:{31,45}]
      if (~s2_replay) begin	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:130:46]
        s2_pc <= s1_pc;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:111:18, :113:22]
        s2_speculative <= s1_speculative;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:112:27, :119:31]
      end
      s2_partial_insn_valid <= ~(s2_redirect | _taken_T_57 & (s2_btb_taken | taken)) & (_taken_T_57 ? _taken_T_61 : s2_partial_insn_valid);	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:116:40, :120:38, :141:32, :300:31, :302:{37,46}, :307:19, :329:{26,43,54}, :330:29, :332:26, :333:20, :337:{31,45}, :342:{24,48}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      wrong_path <= ~io_cpu_req_valid & (taken_taken | s2_btb_taken ? _taken_T_34 | _GEN_7 : _taken_T_57 & taken_taken_1 & ~taken_predictBranch_1 & ~taken_predictJump_1 & ~taken_predictReturn_1 | _taken_T_34 | _GEN_7);	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:116:40, :122:27, :251:71, :253:49, :254:44, :255:41, :257:{88,97}, :262:20, :266:25, :275:30, :276:{44,62,75,78,94}, :277:24, :343:{29,42}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      s2_replay_REG <= s2_replay & ~s0_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:109:35, :130:{46,56,67,70}]
      if (io_cpu_progress)	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:81:14]
        recent_progress_counter <= 2'h3;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:124:29, :151:40]
      else if (_io_cpu_perf_tlbMiss_T & (|recent_progress_counter))	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:151:40, :152:49, :153:24, src/main/scala/chisel3/util/Decoupled.scala:52:35]
        recent_progress_counter <= recent_progress_counter - 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:151:40, :153:97]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:7];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;
        end
        s1_valid = _RANDOM[3'h0][1];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:103:21]
        s2_valid = _RANDOM[3'h0][2];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:103:21, :104:25]
        s1_pc = {_RANDOM[3'h0][31:3], _RANDOM[3'h1][10:0]};	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:103:21, :111:18]
        s1_speculative = _RANDOM[3'h1][11];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:111:18, :112:27]
        s2_pc = {_RANDOM[3'h1][31:12], _RANDOM[3'h2][19:0]};	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:111:18, :113:22]
        s2_btb_resp_valid = _RANDOM[3'h2][20];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:113:22, :114:44]
        s2_btb_resp_bits_taken = _RANDOM[3'h2][23];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:113:22, :115:29]
        s2_btb_resp_bits_bridx = _RANDOM[3'h2][26];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:113:22, :115:29]
        s2_btb_resp_bits_entry = _RANDOM[3'h4][6:2];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29]
        s2_btb_resp_bits_bht_history = _RANDOM[3'h4][14:7];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29]
        taken_predict_taken = _RANDOM[3'h4][15];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29]
        s2_tlb_resp_miss = _RANDOM[3'h4][16];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29, :117:24]
        s2_tlb_resp_pf_inst = _RANDOM[3'h6][28];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24]
        s2_tlb_resp_ae_inst = _RANDOM[3'h7][2];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24]
        s2_tlb_resp_cacheable = _RANDOM[3'h7][6];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24]
        s2_speculative = _RANDOM[3'h7][9];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24, :119:31]
        s2_partial_insn_valid = _RANDOM[3'h7][10];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24, :120:38]
        s2_partial_insn = _RANDOM[3'h7][26:11];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24, :121:28]
        wrong_path = _RANDOM[3'h7][27];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24, :122:27]
        s2_replay_REG = _RANDOM[3'h7][28];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24, :130:56]
        recent_progress_counter = _RANDOM[3'h7][30:29];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24, :151:40]
        fq_io_enq_valid_REG = _RANDOM[3'h7][31];	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24, :180:29]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ICache icache (	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26]
    .clock                          (clock),
    .reset                          (reset),
    .auto_master_out_a_ready        (auto_icache_master_out_a_ready),
    .auto_master_out_a_valid        (auto_icache_master_out_a_valid),
    .auto_master_out_a_bits_address (auto_icache_master_out_a_bits_address),
    .auto_master_out_d_valid        (auto_icache_master_out_d_valid),
    .auto_master_out_d_bits_opcode  (auto_icache_master_out_d_bits_opcode),
    .auto_master_out_d_bits_size    (auto_icache_master_out_d_bits_size),
    .auto_master_out_d_bits_data    (auto_icache_master_out_d_bits_data),
    .auto_master_out_d_bits_corrupt (auto_icache_master_out_d_bits_corrupt),
    .io_req_valid                   (s0_valid),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:109:35]
    .io_req_bits_addr               ({_io_cpu_npc_T[37:0], 1'h0}),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :81:14, :101:19, :170:27, :182:28, :194:21]
    .io_s1_paddr                    (_tlb_io_resp_paddr),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19]
    .io_s1_kill                     (s2_redirect | _tlb_io_resp_miss | s2_replay),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19, :130:46, :141:32, :174:56, :332:26, :333:20, :337:{31,45}]
    .io_s2_kill                     (_icache_io_s2_kill_T_2),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:176:71]
    .io_resp_valid                  (_icache_io_resp_valid),
    .io_resp_bits_data              (_icache_io_resp_bits_data),
    .io_resp_bits_ae                (_icache_io_resp_bits_ae),
    .io_invalidate                  (io_cpu_flush_icache),
    .io_perf_acquire                (io_cpu_perf_acquire)
  );
  ShiftQueue fq (	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:87:64]
    .clock                       (clock),
    .reset                       (reset | io_cpu_req_valid),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:87:35]
    .io_enq_ready                (_fq_io_enq_ready),
    .io_enq_valid                (_fq_io_enq_valid_T_6),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:180:52]
    .io_enq_bits_btb_taken       (_GEN_6 | s2_btb_taken),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:116:40, :187:22, :188:28, :332:26, :333:20, :334:34, :335:34]
    .io_enq_bits_btb_bridx       (_GEN_6 ? ~taken_taken : s2_btb_resp_bits_bridx),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29, :187:22, :251:71, :266:13, :332:26, :333:20, :334:34]
    .io_enq_bits_btb_entry       (_GEN_6 ? 5'h1C : s2_btb_resp_bits_entry),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29, :187:22, :316:47, :332:26, :333:20, :334:34, :336:34]
    .io_enq_bits_btb_bht_history (s2_btb_resp_bits_bht_history),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29]
    .io_enq_bits_pc              (s2_pc),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:113:22]
    .io_enq_bits_data            (_icache_io_resp_bits_data),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26]
    .io_enq_bits_xcpt_pf_inst    (s2_tlb_resp_pf_inst),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:117:24]
    .io_enq_bits_xcpt_ae_inst    (_icache_io_resp_valid & _icache_io_resp_bits_ae | s2_tlb_resp_ae_inst),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :117:24, :189:23, :191:{30,57,87}]
    .io_enq_bits_replay          (_taken_T_34 | _taken_T_5 | _icache_io_s2_kill_T_2 & ~_icache_io_resp_valid & ~_s2_xcpt_T | _fq_io_enq_bits_replay_T_5),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :118:37, :176:71, :180:112, :186:{25,80,102,105}, :257:{88,97}, :261:31]
    .io_deq_ready                (io_cpu_resp_ready),
    .io_deq_valid                (io_cpu_resp_valid),
    .io_deq_bits_btb_taken       (io_cpu_resp_bits_btb_taken),
    .io_deq_bits_btb_bridx       (io_cpu_resp_bits_btb_bridx),
    .io_deq_bits_btb_entry       (io_cpu_resp_bits_btb_entry),
    .io_deq_bits_btb_bht_history (io_cpu_resp_bits_btb_bht_history),
    .io_deq_bits_pc              (io_cpu_resp_bits_pc),
    .io_deq_bits_data            (io_cpu_resp_bits_data),
    .io_deq_bits_xcpt_pf_inst    (io_cpu_resp_bits_xcpt_pf_inst),
    .io_deq_bits_xcpt_gf_inst    (io_cpu_resp_bits_xcpt_gf_inst),
    .io_deq_bits_xcpt_ae_inst    (io_cpu_resp_bits_xcpt_ae_inst),
    .io_deq_bits_replay          (io_cpu_resp_bits_replay),
    .io_mask                     (_fq_io_mask)
  );
  TLB_2 tlb (	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19]
    .clock                         (clock),
    .reset                         (reset),
    .io_req_valid                  (s1_valid & ~s2_replay),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:103:21, :130:46, :143:9, :159:32]
    .io_req_bits_vaddr             (s1_pc),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:111:18]
    .io_req_bits_prv               (io_ptw_status_prv),
    .io_resp_miss                  (_tlb_io_resp_miss),
    .io_resp_paddr                 (_tlb_io_resp_paddr),
    .io_resp_pf_inst               (_tlb_io_resp_pf_inst),
    .io_resp_ae_inst               (_tlb_io_resp_ae_inst),
    .io_resp_cacheable             (_tlb_io_resp_cacheable),
    .io_sfence_valid               (io_cpu_sfence_valid),
    .io_sfence_bits_rs1            (io_cpu_sfence_bits_rs1),
    .io_sfence_bits_rs2            (io_cpu_sfence_bits_rs2),
    .io_sfence_bits_addr           (io_cpu_sfence_bits_addr),
    .io_ptw_req_ready              (io_ptw_req_ready),
    .io_ptw_req_valid              (_tlb_io_ptw_req_valid),
    .io_ptw_req_bits_valid         (io_ptw_req_bits_valid),
    .io_ptw_req_bits_bits_addr     (io_ptw_req_bits_bits_addr),
    .io_ptw_req_bits_bits_need_gpa (io_ptw_req_bits_bits_need_gpa),
    .io_ptw_resp_valid             (io_ptw_resp_valid),
    .io_ptw_resp_bits_ae_ptw       (io_ptw_resp_bits_ae_ptw),
    .io_ptw_resp_bits_ae_final     (io_ptw_resp_bits_ae_final),
    .io_ptw_resp_bits_pf           (io_ptw_resp_bits_pf),
    .io_ptw_resp_bits_gf           (io_ptw_resp_bits_gf),
    .io_ptw_resp_bits_hr           (io_ptw_resp_bits_hr),
    .io_ptw_resp_bits_hw           (io_ptw_resp_bits_hw),
    .io_ptw_resp_bits_hx           (io_ptw_resp_bits_hx),
    .io_ptw_resp_bits_pte_ppn      (io_ptw_resp_bits_pte_ppn),
    .io_ptw_resp_bits_pte_d        (io_ptw_resp_bits_pte_d),
    .io_ptw_resp_bits_pte_a        (io_ptw_resp_bits_pte_a),
    .io_ptw_resp_bits_pte_g        (io_ptw_resp_bits_pte_g),
    .io_ptw_resp_bits_pte_u        (io_ptw_resp_bits_pte_u),
    .io_ptw_resp_bits_pte_x        (io_ptw_resp_bits_pte_x),
    .io_ptw_resp_bits_pte_w        (io_ptw_resp_bits_pte_w),
    .io_ptw_resp_bits_pte_r        (io_ptw_resp_bits_pte_r),
    .io_ptw_resp_bits_pte_v        (io_ptw_resp_bits_pte_v),
    .io_ptw_resp_bits_level        (io_ptw_resp_bits_level),
    .io_ptw_resp_bits_homogeneous  (io_ptw_resp_bits_homogeneous),
    .io_ptw_ptbr_mode              (io_ptw_ptbr_mode),
    .io_ptw_status_debug           (io_ptw_status_debug),
    .io_ptw_pmp_0_cfg_l            (io_ptw_pmp_0_cfg_l),
    .io_ptw_pmp_0_cfg_a            (io_ptw_pmp_0_cfg_a),
    .io_ptw_pmp_0_cfg_x            (io_ptw_pmp_0_cfg_x),
    .io_ptw_pmp_0_cfg_w            (io_ptw_pmp_0_cfg_w),
    .io_ptw_pmp_0_cfg_r            (io_ptw_pmp_0_cfg_r),
    .io_ptw_pmp_0_addr             (io_ptw_pmp_0_addr),
    .io_ptw_pmp_0_mask             (io_ptw_pmp_0_mask),
    .io_ptw_pmp_1_cfg_l            (io_ptw_pmp_1_cfg_l),
    .io_ptw_pmp_1_cfg_a            (io_ptw_pmp_1_cfg_a),
    .io_ptw_pmp_1_cfg_x            (io_ptw_pmp_1_cfg_x),
    .io_ptw_pmp_1_cfg_w            (io_ptw_pmp_1_cfg_w),
    .io_ptw_pmp_1_cfg_r            (io_ptw_pmp_1_cfg_r),
    .io_ptw_pmp_1_addr             (io_ptw_pmp_1_addr),
    .io_ptw_pmp_1_mask             (io_ptw_pmp_1_mask),
    .io_ptw_pmp_2_cfg_l            (io_ptw_pmp_2_cfg_l),
    .io_ptw_pmp_2_cfg_a            (io_ptw_pmp_2_cfg_a),
    .io_ptw_pmp_2_cfg_x            (io_ptw_pmp_2_cfg_x),
    .io_ptw_pmp_2_cfg_w            (io_ptw_pmp_2_cfg_w),
    .io_ptw_pmp_2_cfg_r            (io_ptw_pmp_2_cfg_r),
    .io_ptw_pmp_2_addr             (io_ptw_pmp_2_addr),
    .io_ptw_pmp_2_mask             (io_ptw_pmp_2_mask),
    .io_ptw_pmp_3_cfg_l            (io_ptw_pmp_3_cfg_l),
    .io_ptw_pmp_3_cfg_a            (io_ptw_pmp_3_cfg_a),
    .io_ptw_pmp_3_cfg_x            (io_ptw_pmp_3_cfg_x),
    .io_ptw_pmp_3_cfg_w            (io_ptw_pmp_3_cfg_w),
    .io_ptw_pmp_3_cfg_r            (io_ptw_pmp_3_cfg_r),
    .io_ptw_pmp_3_addr             (io_ptw_pmp_3_addr),
    .io_ptw_pmp_3_mask             (io_ptw_pmp_3_mask),
    .io_ptw_pmp_4_cfg_l            (io_ptw_pmp_4_cfg_l),
    .io_ptw_pmp_4_cfg_a            (io_ptw_pmp_4_cfg_a),
    .io_ptw_pmp_4_cfg_x            (io_ptw_pmp_4_cfg_x),
    .io_ptw_pmp_4_cfg_w            (io_ptw_pmp_4_cfg_w),
    .io_ptw_pmp_4_cfg_r            (io_ptw_pmp_4_cfg_r),
    .io_ptw_pmp_4_addr             (io_ptw_pmp_4_addr),
    .io_ptw_pmp_4_mask             (io_ptw_pmp_4_mask),
    .io_ptw_pmp_5_cfg_l            (io_ptw_pmp_5_cfg_l),
    .io_ptw_pmp_5_cfg_a            (io_ptw_pmp_5_cfg_a),
    .io_ptw_pmp_5_cfg_x            (io_ptw_pmp_5_cfg_x),
    .io_ptw_pmp_5_cfg_w            (io_ptw_pmp_5_cfg_w),
    .io_ptw_pmp_5_cfg_r            (io_ptw_pmp_5_cfg_r),
    .io_ptw_pmp_5_addr             (io_ptw_pmp_5_addr),
    .io_ptw_pmp_5_mask             (io_ptw_pmp_5_mask),
    .io_ptw_pmp_6_cfg_l            (io_ptw_pmp_6_cfg_l),
    .io_ptw_pmp_6_cfg_a            (io_ptw_pmp_6_cfg_a),
    .io_ptw_pmp_6_cfg_x            (io_ptw_pmp_6_cfg_x),
    .io_ptw_pmp_6_cfg_w            (io_ptw_pmp_6_cfg_w),
    .io_ptw_pmp_6_cfg_r            (io_ptw_pmp_6_cfg_r),
    .io_ptw_pmp_6_addr             (io_ptw_pmp_6_addr),
    .io_ptw_pmp_6_mask             (io_ptw_pmp_6_mask),
    .io_ptw_pmp_7_cfg_l            (io_ptw_pmp_7_cfg_l),
    .io_ptw_pmp_7_cfg_a            (io_ptw_pmp_7_cfg_a),
    .io_ptw_pmp_7_cfg_x            (io_ptw_pmp_7_cfg_x),
    .io_ptw_pmp_7_cfg_w            (io_ptw_pmp_7_cfg_w),
    .io_ptw_pmp_7_cfg_r            (io_ptw_pmp_7_cfg_r),
    .io_ptw_pmp_7_addr             (io_ptw_pmp_7_addr),
    .io_ptw_pmp_7_mask             (io_ptw_pmp_7_mask),
    .io_kill                       (~s2_valid | s2_kill_speculative_tlb_refill)	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:104:25, :107:58, :156:55, :167:28]
  );
  BTB btb (	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:194:21]
    .clock                                 (clock),
    .reset                                 (reset),
    .io_req_bits_addr                      (s1_pc[38:0]),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:111:18, :197:26]
    .io_resp_valid                         (_btb_io_resp_valid),
    .io_resp_bits_taken                    (_btb_io_resp_bits_taken),
    .io_resp_bits_bridx                    (_btb_io_resp_bits_bridx),
    .io_resp_bits_target                   (_btb_io_resp_bits_target),
    .io_resp_bits_entry                    (_btb_io_resp_bits_entry),
    .io_resp_bits_bht_history              (_btb_io_resp_bits_bht_history),
    .io_resp_bits_bht_value                (_btb_io_resp_bits_bht_value),
    .io_btb_update_valid                   (io_cpu_btb_update_valid ? io_cpu_btb_update_valid : _taken_T_57 & ~wrong_path & ~(_fq_io_mask[1]) & updateBTB),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:87:64, :122:27, :198:23, :266:25, :294:125, :295:21, :313:37, :314:{33,44}, :315:{31,52,87}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
    .io_btb_update_bits_prediction_entry   (io_cpu_btb_update_valid ? io_cpu_btb_update_bits_prediction_entry : 5'h1C),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:198:23, :313:37, :316:47]
    .io_btb_update_bits_pc                 (io_cpu_btb_update_valid ? io_cpu_btb_update_bits_pc : _GEN_0),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:198:23, :313:37, :320:33]
    .io_btb_update_bits_isValid            (~io_cpu_btb_update_valid | io_cpu_btb_update_bits_isValid),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:198:23, :313:{11,37}, :317:38]
    .io_btb_update_bits_br_pc              (io_cpu_btb_update_valid ? io_cpu_btb_update_bits_br_pc : {s2_pc[38:2], ~taken_taken, 1'h0}),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :81:14, :101:19, :113:22, :194:21, :198:23, :251:71, :266:13, :313:37, :319:36]
    .io_btb_update_bits_cfiType            (io_cpu_btb_update_valid ? io_cpu_btb_update_bits_cfiType : _GEN),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:198:23, :266:25, :270:40, :313:37, :318:38]
    .io_bht_update_valid                   (io_cpu_bht_update_valid),
    .io_bht_update_bits_prediction_history (io_cpu_bht_update_bits_prediction_history),
    .io_bht_update_bits_pc                 (io_cpu_bht_update_bits_pc),
    .io_bht_update_bits_branch             (io_cpu_bht_update_bits_branch),
    .io_bht_update_bits_taken              (io_cpu_bht_update_bits_taken),
    .io_bht_update_bits_mispredict         (io_cpu_bht_update_bits_mispredict),
    .io_bht_advance_valid                  (~taken_taken & (_taken_T_48 | _taken_T_49) ? _taken_T_57 & ~wrong_path : (_taken_T_19 | _taken_T_20) & _taken_T_57 & ~wrong_path),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:122:27, :202:30, :251:71, :255:{53,75}, :266:{13,25}, :269:54, :290:{36,59}, :291:{36,54}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
    .io_bht_advance_bits_bht_value         (taken_predict_taken),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:115:29]
    .io_ras_update_valid                   (taken_taken ? _taken_T_57 & ~wrong_path & (taken_prevRVI & (taken_rviCall | taken_rviReturn) | taken_valid & (taken_rvcJALR | taken_rvcReturn)) : _taken_T_57 & ~wrong_path & (taken_prevRVI_1 & (taken_rviCall_1 | taken_rviReturn_1) | taken_valid_1 & (taken_rvcJALR_1 | taken_rvcReturn_1))),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:122:27, :230:31, :231:44, :238:46, :239:42, :245:29, :246:49, :251:71, :266:25, :269:{33,54,66,78,90,104,113,125}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
    .io_ras_update_bits_cfiType            (_GEN),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:266:25, :270:40]
    .io_ras_update_bits_returnAddr         (_GEN_0 + {36'h0, after_idx, 1'h0}),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/rocket/Frontend.scala:66:26, :81:14, :101:19, :194:21, :266:25, :268:19, :320:33, :323:53]
    .io_ras_head_valid                     (_btb_io_ras_head_valid),
    .io_ras_head_bits                      (_btb_io_ras_head_bits),
    .io_flush                              (_taken_T_34 | _taken_T_5)	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:257:{88,97}, :260:22]
  );
  assign io_cpu_perf_tlbMiss = _io_cpu_perf_tlbMiss_T;	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
  assign io_ptw_req_valid = _tlb_io_ptw_req_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:101:19]
endmodule

