// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module DataArray(
  input         clock,
                io_read_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
  input  [15:0] io_read_bits_way_en,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
  input  [11:0] io_read_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
  input         io_write_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
  input  [15:0] io_write_bits_way_en,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
  input  [11:0] io_write_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
  input  [63:0] io_write_bits_data,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
  output [63:0] io_resp_0,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_1,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_2,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_3,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_4,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_5,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_6,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_7,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_8,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_9,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_10,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_11,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_12,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_13,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_14,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
                io_resp_15	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:727:14]
);

  array_0_0_0 array_0_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[0] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_0),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[0] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_1_0_0 array_1_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[1] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_1),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[1] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_2_0_0 array_2_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[2] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_2),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[2] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_3_0_0 array_3_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[3] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_3),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[3] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_4_0_0 array_4_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[4] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_4),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[4] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_5_0_0 array_5_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[5] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_5),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[5] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_6_0_0 array_6_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[6] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_6),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[6] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_7_0_0 array_7_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[7] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_7),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[7] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_8_0_0 array_8_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[8] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_8),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[8] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_9_0_0 array_9_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[9] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_9),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[9] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_10_0_0 array_10_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[10] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_10),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[10] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_11_0_0 array_11_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[11] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_11),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[11] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_12_0_0 array_12_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[12] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_12),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[12] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_13_0_0 array_13_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[13] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_13),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[13] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_14_0_0 array_14_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[14] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_14),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[14] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
  array_15_0_0 array_15_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:734:33]
    .R0_en   (io_read_bits_way_en[15] & io_read_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:746:40, :760:50]
    .R0_clk  (clock),
    .R0_data (io_resp_15),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:733:34]
    .W0_en   (io_write_bits_way_en[15] & io_write_valid),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:745:41, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );
endmodule

