// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module IOMSHR(
  input         clock,
                reset,
  output        io_req_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input         io_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input  [39:0] io_req_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input  [6:0]  io_req_bits_tag,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input  [4:0]  io_req_bits_cmd,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input  [1:0]  io_req_bits_size,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input         io_req_bits_signed,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input  [1:0]  io_req_bits_dprv,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input         io_req_bits_dv,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
                io_req_bits_isLookup,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input  [63:0] io_req_bits_data,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input  [7:0]  io_req_bits_mask,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input         io_resp_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output        io_resp_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [39:0] io_resp_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [6:0]  io_resp_bits_tag,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [4:0]  io_resp_bits_cmd,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [1:0]  io_resp_bits_size,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output        io_resp_bits_signed,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [1:0]  io_resp_bits_dprv,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output        io_resp_bits_dv,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
                io_resp_bits_isLookup,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [63:0] io_resp_bits_data,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [7:0]  io_resp_bits_mask,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output        io_resp_bits_has_data,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [63:0] io_resp_bits_store_data,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input         io_mem_access_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output        io_mem_access_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [2:0]  io_mem_access_bits_opcode,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
                io_mem_access_bits_param,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [3:0]  io_mem_access_bits_size,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [2:0]  io_mem_access_bits_source,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [31:0] io_mem_access_bits_address,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [7:0]  io_mem_access_bits_mask,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output [63:0] io_mem_access_bits_data,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input         io_mem_ack_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  input  [63:0] io_mem_ack_bits_data,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
  output        io_replay_next	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:57:14]
);

  reg  [39:0] req_addr;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  reg  [6:0]  req_tag;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  reg  [4:0]  req_cmd;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  reg  [1:0]  req_size;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  reg         req_signed;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  reg  [1:0]  req_dprv;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  reg         req_dv;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  reg         req_isLookup;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  reg  [63:0] req_data;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  reg  [7:0]  req_mask;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  reg  [63:0] grant_word;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:73:23]
  reg  [1:0]  state;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:76:22]
  wire        _io_req_ready_output = state == 2'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:76:22, :77:26]
  wire        get_a_mask_size = req_size == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        get_a_mask_acc = (&req_size) | get_a_mask_size & ~(req_addr[2]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire        get_a_mask_acc_1 = (&req_size) | get_a_mask_size & req_addr[2];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire        get_a_mask_size_1 = req_size == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :111:33, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        get_a_mask_eq_2 = ~(req_addr[2]) & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        get_a_mask_acc_2 = get_a_mask_acc | get_a_mask_size_1 & get_a_mask_eq_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        get_a_mask_eq_3 = ~(req_addr[2]) & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        get_a_mask_acc_3 = get_a_mask_acc | get_a_mask_size_1 & get_a_mask_eq_3;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        get_a_mask_eq_4 = req_addr[2] & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        get_a_mask_acc_4 = get_a_mask_acc_1 | get_a_mask_size_1 & get_a_mask_eq_4;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        get_a_mask_eq_5 = req_addr[2] & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        get_a_mask_acc_5 = get_a_mask_acc_1 | get_a_mask_size_1 & get_a_mask_eq_5;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        put_a_mask_size = req_size == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        put_a_mask_acc = (&req_size) | put_a_mask_size & ~(req_addr[2]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire        put_a_mask_acc_1 = (&req_size) | put_a_mask_size & req_addr[2];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire        put_a_mask_size_1 = req_size == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :111:33, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        put_a_mask_eq_2 = ~(req_addr[2]) & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        put_a_mask_acc_2 = put_a_mask_acc | put_a_mask_size_1 & put_a_mask_eq_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        put_a_mask_eq_3 = ~(req_addr[2]) & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        put_a_mask_acc_3 = put_a_mask_acc | put_a_mask_size_1 & put_a_mask_eq_3;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        put_a_mask_eq_4 = req_addr[2] & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        put_a_mask_acc_4 = put_a_mask_acc_1 | put_a_mask_size_1 & put_a_mask_eq_4;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        put_a_mask_eq_5 = req_addr[2] & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        put_a_mask_acc_5 = put_a_mask_acc_1 | put_a_mask_size_1 & put_a_mask_eq_5;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_size = req_size == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_acc = (&req_size) | atomics_a_mask_size & ~(req_addr[2]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire        atomics_a_mask_acc_1 = (&req_size) | atomics_a_mask_size & req_addr[2];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire        atomics_a_mask_size_1 = req_size == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :111:33, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_eq_2 = ~(req_addr[2]) & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_2 = atomics_a_mask_acc | atomics_a_mask_size_1 & atomics_a_mask_eq_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_3 = ~(req_addr[2]) & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_3 = atomics_a_mask_acc | atomics_a_mask_size_1 & atomics_a_mask_eq_3;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_4 = req_addr[2] & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_4 = atomics_a_mask_acc_1 | atomics_a_mask_size_1 & atomics_a_mask_eq_4;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_5 = req_addr[2] & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        atomics_a_mask_acc_5 = atomics_a_mask_acc_1 | atomics_a_mask_size_1 & atomics_a_mask_eq_5;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_size_3 = req_size == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_acc_14 = (&req_size) | atomics_a_mask_size_3 & ~(req_addr[2]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire        atomics_a_mask_acc_15 = (&req_size) | atomics_a_mask_size_3 & req_addr[2];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire        atomics_a_mask_size_4 = req_size == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :111:33, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_eq_16 = ~(req_addr[2]) & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_16 = atomics_a_mask_acc_14 | atomics_a_mask_size_4 & atomics_a_mask_eq_16;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_17 = ~(req_addr[2]) & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_17 = atomics_a_mask_acc_14 | atomics_a_mask_size_4 & atomics_a_mask_eq_17;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_18 = req_addr[2] & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_18 = atomics_a_mask_acc_15 | atomics_a_mask_size_4 & atomics_a_mask_eq_18;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_19 = req_addr[2] & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        atomics_a_mask_acc_19 = atomics_a_mask_acc_15 | atomics_a_mask_size_4 & atomics_a_mask_eq_19;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_size_6 = req_size == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_acc_28 = (&req_size) | atomics_a_mask_size_6 & ~(req_addr[2]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire        atomics_a_mask_acc_29 = (&req_size) | atomics_a_mask_size_6 & req_addr[2];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire        atomics_a_mask_size_7 = req_size == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :111:33, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_eq_30 = ~(req_addr[2]) & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_30 = atomics_a_mask_acc_28 | atomics_a_mask_size_7 & atomics_a_mask_eq_30;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_31 = ~(req_addr[2]) & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_31 = atomics_a_mask_acc_28 | atomics_a_mask_size_7 & atomics_a_mask_eq_31;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_32 = req_addr[2] & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_32 = atomics_a_mask_acc_29 | atomics_a_mask_size_7 & atomics_a_mask_eq_32;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_33 = req_addr[2] & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        atomics_a_mask_acc_33 = atomics_a_mask_acc_29 | atomics_a_mask_size_7 & atomics_a_mask_eq_33;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_size_9 = req_size == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_acc_42 = (&req_size) | atomics_a_mask_size_9 & ~(req_addr[2]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire        atomics_a_mask_acc_43 = (&req_size) | atomics_a_mask_size_9 & req_addr[2];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire        atomics_a_mask_size_10 = req_size == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :111:33, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_eq_44 = ~(req_addr[2]) & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_44 = atomics_a_mask_acc_42 | atomics_a_mask_size_10 & atomics_a_mask_eq_44;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_45 = ~(req_addr[2]) & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_45 = atomics_a_mask_acc_42 | atomics_a_mask_size_10 & atomics_a_mask_eq_45;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_46 = req_addr[2] & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_46 = atomics_a_mask_acc_43 | atomics_a_mask_size_10 & atomics_a_mask_eq_46;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_47 = req_addr[2] & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        atomics_a_mask_acc_47 = atomics_a_mask_acc_43 | atomics_a_mask_size_10 & atomics_a_mask_eq_47;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_size_12 = req_size == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_acc_56 = (&req_size) | atomics_a_mask_size_12 & ~(req_addr[2]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire        atomics_a_mask_acc_57 = (&req_size) | atomics_a_mask_size_12 & req_addr[2];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire        atomics_a_mask_size_13 = req_size == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :111:33, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_eq_58 = ~(req_addr[2]) & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_58 = atomics_a_mask_acc_56 | atomics_a_mask_size_13 & atomics_a_mask_eq_58;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_59 = ~(req_addr[2]) & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_59 = atomics_a_mask_acc_56 | atomics_a_mask_size_13 & atomics_a_mask_eq_59;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_60 = req_addr[2] & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_60 = atomics_a_mask_acc_57 | atomics_a_mask_size_13 & atomics_a_mask_eq_60;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_61 = req_addr[2] & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        atomics_a_mask_acc_61 = atomics_a_mask_acc_57 | atomics_a_mask_size_13 & atomics_a_mask_eq_61;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_size_15 = req_size == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_acc_70 = (&req_size) | atomics_a_mask_size_15 & ~(req_addr[2]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire        atomics_a_mask_acc_71 = (&req_size) | atomics_a_mask_size_15 & req_addr[2];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire        atomics_a_mask_size_16 = req_size == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :111:33, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_eq_72 = ~(req_addr[2]) & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_72 = atomics_a_mask_acc_70 | atomics_a_mask_size_16 & atomics_a_mask_eq_72;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_73 = ~(req_addr[2]) & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_73 = atomics_a_mask_acc_70 | atomics_a_mask_size_16 & atomics_a_mask_eq_73;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_74 = req_addr[2] & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_74 = atomics_a_mask_acc_71 | atomics_a_mask_size_16 & atomics_a_mask_eq_74;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_75 = req_addr[2] & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        atomics_a_mask_acc_75 = atomics_a_mask_acc_71 | atomics_a_mask_size_16 & atomics_a_mask_eq_75;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_size_18 = req_size == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_acc_84 = (&req_size) | atomics_a_mask_size_18 & ~(req_addr[2]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire        atomics_a_mask_acc_85 = (&req_size) | atomics_a_mask_size_18 & req_addr[2];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire        atomics_a_mask_size_19 = req_size == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :111:33, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_eq_86 = ~(req_addr[2]) & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_86 = atomics_a_mask_acc_84 | atomics_a_mask_size_19 & atomics_a_mask_eq_86;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_87 = ~(req_addr[2]) & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_87 = atomics_a_mask_acc_84 | atomics_a_mask_size_19 & atomics_a_mask_eq_87;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_88 = req_addr[2] & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_88 = atomics_a_mask_acc_85 | atomics_a_mask_size_19 & atomics_a_mask_eq_88;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_89 = req_addr[2] & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        atomics_a_mask_acc_89 = atomics_a_mask_acc_85 | atomics_a_mask_size_19 & atomics_a_mask_eq_89;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_size_21 = req_size == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_acc_98 = (&req_size) | atomics_a_mask_size_21 & ~(req_addr[2]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire        atomics_a_mask_acc_99 = (&req_size) | atomics_a_mask_size_21 & req_addr[2];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire        atomics_a_mask_size_22 = req_size == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :111:33, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_eq_100 = ~(req_addr[2]) & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_100 = atomics_a_mask_acc_98 | atomics_a_mask_size_22 & atomics_a_mask_eq_100;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_101 = ~(req_addr[2]) & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_101 = atomics_a_mask_acc_98 | atomics_a_mask_size_22 & atomics_a_mask_eq_101;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_102 = req_addr[2] & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_102 = atomics_a_mask_acc_99 | atomics_a_mask_size_22 & atomics_a_mask_eq_102;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_103 = req_addr[2] & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        atomics_a_mask_acc_103 = atomics_a_mask_acc_99 | atomics_a_mask_size_22 & atomics_a_mask_eq_103;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_size_24 = req_size == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_acc_112 = (&req_size) | atomics_a_mask_size_24 & ~(req_addr[2]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire        atomics_a_mask_acc_113 = (&req_size) | atomics_a_mask_size_24 & req_addr[2];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire        atomics_a_mask_size_25 = req_size == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :111:33, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        atomics_a_mask_eq_114 = ~(req_addr[2]) & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_114 = atomics_a_mask_acc_112 | atomics_a_mask_size_25 & atomics_a_mask_eq_114;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_115 = ~(req_addr[2]) & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_115 = atomics_a_mask_acc_112 | atomics_a_mask_size_25 & atomics_a_mask_eq_115;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_116 = req_addr[2] & ~(req_addr[1]);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        atomics_a_mask_acc_116 = atomics_a_mask_acc_113 | atomics_a_mask_size_25 & atomics_a_mask_eq_116;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        atomics_a_mask_eq_117 = req_addr[2] & req_addr[1];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        atomics_a_mask_acc_117 = atomics_a_mask_acc_113 | atomics_a_mask_size_25 & atomics_a_mask_eq_117;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        _atomics_T = req_cmd == 5'h4;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _atomics_T_2 = req_cmd == 5'h9;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _atomics_T_4 = req_cmd == 5'hA;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _atomics_T_6 = req_cmd == 5'hB;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _GEN = _atomics_T_6 | _atomics_T_4 | _atomics_T_2 | _atomics_T;	// @[src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _atomics_T_8 = req_cmd == 5'h8;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _atomics_T_10 = req_cmd == 5'hC;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _atomics_T_12 = req_cmd == 5'hD;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _atomics_T_14 = req_cmd == 5'hE;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _atomics_T_16 = req_cmd == 5'hF;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire [7:0]  atomics_mask =
    _atomics_T_16
      ? {atomics_a_mask_acc_117 | atomics_a_mask_eq_117 & req_addr[0], atomics_a_mask_acc_117 | atomics_a_mask_eq_117 & ~(req_addr[0]), atomics_a_mask_acc_116 | atomics_a_mask_eq_116 & req_addr[0], atomics_a_mask_acc_116 | atomics_a_mask_eq_116 & ~(req_addr[0]), atomics_a_mask_acc_115 | atomics_a_mask_eq_115 & req_addr[0], atomics_a_mask_acc_115 | atomics_a_mask_eq_115 & ~(req_addr[0]), atomics_a_mask_acc_114 | atomics_a_mask_eq_114 & req_addr[0], atomics_a_mask_acc_114 | atomics_a_mask_eq_114 & ~(req_addr[0])}
      : _atomics_T_14
          ? {atomics_a_mask_acc_103 | atomics_a_mask_eq_103 & req_addr[0], atomics_a_mask_acc_103 | atomics_a_mask_eq_103 & ~(req_addr[0]), atomics_a_mask_acc_102 | atomics_a_mask_eq_102 & req_addr[0], atomics_a_mask_acc_102 | atomics_a_mask_eq_102 & ~(req_addr[0]), atomics_a_mask_acc_101 | atomics_a_mask_eq_101 & req_addr[0], atomics_a_mask_acc_101 | atomics_a_mask_eq_101 & ~(req_addr[0]), atomics_a_mask_acc_100 | atomics_a_mask_eq_100 & req_addr[0], atomics_a_mask_acc_100 | atomics_a_mask_eq_100 & ~(req_addr[0])}
          : _atomics_T_12
              ? {atomics_a_mask_acc_89 | atomics_a_mask_eq_89 & req_addr[0], atomics_a_mask_acc_89 | atomics_a_mask_eq_89 & ~(req_addr[0]), atomics_a_mask_acc_88 | atomics_a_mask_eq_88 & req_addr[0], atomics_a_mask_acc_88 | atomics_a_mask_eq_88 & ~(req_addr[0]), atomics_a_mask_acc_87 | atomics_a_mask_eq_87 & req_addr[0], atomics_a_mask_acc_87 | atomics_a_mask_eq_87 & ~(req_addr[0]), atomics_a_mask_acc_86 | atomics_a_mask_eq_86 & req_addr[0], atomics_a_mask_acc_86 | atomics_a_mask_eq_86 & ~(req_addr[0])}
              : _atomics_T_10
                  ? {atomics_a_mask_acc_75 | atomics_a_mask_eq_75 & req_addr[0], atomics_a_mask_acc_75 | atomics_a_mask_eq_75 & ~(req_addr[0]), atomics_a_mask_acc_74 | atomics_a_mask_eq_74 & req_addr[0], atomics_a_mask_acc_74 | atomics_a_mask_eq_74 & ~(req_addr[0]), atomics_a_mask_acc_73 | atomics_a_mask_eq_73 & req_addr[0], atomics_a_mask_acc_73 | atomics_a_mask_eq_73 & ~(req_addr[0]), atomics_a_mask_acc_72 | atomics_a_mask_eq_72 & req_addr[0], atomics_a_mask_acc_72 | atomics_a_mask_eq_72 & ~(req_addr[0])}
                  : _atomics_T_8
                      ? {atomics_a_mask_acc_61 | atomics_a_mask_eq_61 & req_addr[0], atomics_a_mask_acc_61 | atomics_a_mask_eq_61 & ~(req_addr[0]), atomics_a_mask_acc_60 | atomics_a_mask_eq_60 & req_addr[0], atomics_a_mask_acc_60 | atomics_a_mask_eq_60 & ~(req_addr[0]), atomics_a_mask_acc_59 | atomics_a_mask_eq_59 & req_addr[0], atomics_a_mask_acc_59 | atomics_a_mask_eq_59 & ~(req_addr[0]), atomics_a_mask_acc_58 | atomics_a_mask_eq_58 & req_addr[0], atomics_a_mask_acc_58 | atomics_a_mask_eq_58 & ~(req_addr[0])}
                      : _atomics_T_6
                          ? {atomics_a_mask_acc_47 | atomics_a_mask_eq_47 & req_addr[0], atomics_a_mask_acc_47 | atomics_a_mask_eq_47 & ~(req_addr[0]), atomics_a_mask_acc_46 | atomics_a_mask_eq_46 & req_addr[0], atomics_a_mask_acc_46 | atomics_a_mask_eq_46 & ~(req_addr[0]), atomics_a_mask_acc_45 | atomics_a_mask_eq_45 & req_addr[0], atomics_a_mask_acc_45 | atomics_a_mask_eq_45 & ~(req_addr[0]), atomics_a_mask_acc_44 | atomics_a_mask_eq_44 & req_addr[0], atomics_a_mask_acc_44 | atomics_a_mask_eq_44 & ~(req_addr[0])}
                          : _atomics_T_4 ? {atomics_a_mask_acc_33 | atomics_a_mask_eq_33 & req_addr[0], atomics_a_mask_acc_33 | atomics_a_mask_eq_33 & ~(req_addr[0]), atomics_a_mask_acc_32 | atomics_a_mask_eq_32 & req_addr[0], atomics_a_mask_acc_32 | atomics_a_mask_eq_32 & ~(req_addr[0]), atomics_a_mask_acc_31 | atomics_a_mask_eq_31 & req_addr[0], atomics_a_mask_acc_31 | atomics_a_mask_eq_31 & ~(req_addr[0]), atomics_a_mask_acc_30 | atomics_a_mask_eq_30 & req_addr[0], atomics_a_mask_acc_30 | atomics_a_mask_eq_30 & ~(req_addr[0])} : _atomics_T_2 ? {atomics_a_mask_acc_19 | atomics_a_mask_eq_19 & req_addr[0], atomics_a_mask_acc_19 | atomics_a_mask_eq_19 & ~(req_addr[0]), atomics_a_mask_acc_18 | atomics_a_mask_eq_18 & req_addr[0], atomics_a_mask_acc_18 | atomics_a_mask_eq_18 & ~(req_addr[0]), atomics_a_mask_acc_17 | atomics_a_mask_eq_17 & req_addr[0], atomics_a_mask_acc_17 | atomics_a_mask_eq_17 & ~(req_addr[0]), atomics_a_mask_acc_16 | atomics_a_mask_eq_16 & req_addr[0], atomics_a_mask_acc_16 | atomics_a_mask_eq_16 & ~(req_addr[0])} : _atomics_T ? {atomics_a_mask_acc_5 | atomics_a_mask_eq_5 & req_addr[0], atomics_a_mask_acc_5 | atomics_a_mask_eq_5 & ~(req_addr[0]), atomics_a_mask_acc_4 | atomics_a_mask_eq_4 & req_addr[0], atomics_a_mask_acc_4 | atomics_a_mask_eq_4 & ~(req_addr[0]), atomics_a_mask_acc_3 | atomics_a_mask_eq_3 & req_addr[0], atomics_a_mask_acc_3 | atomics_a_mask_eq_3 & ~(req_addr[0]), atomics_a_mask_acc_2 | atomics_a_mask_eq_2 & req_addr[0], atomics_a_mask_acc_2 | atomics_a_mask_eq_2 & ~(req_addr[0])} : 8'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :94:38, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27, :215:29, :222:10, src/main/scala/chisel3/util/Mux.scala:77:13]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:109:9]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:109:9]
      if (~reset & ~(_io_req_ready_output | req_cmd != 5'h7)) begin	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :77:26, :109:{9,27,38}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:109:9]
          $error("Assertion failed\n    at NBDcache.scala:109 assert(state === s_idle || req.cmd =/= M_XSC)\n");	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:109:9]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:109:9]
          $fatal;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:109:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _io_mem_access_valid_output = state == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:76:22, :111:33]
  wire        _io_resp_bits_has_data_T_7 = req_cmd == 5'h4;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _io_resp_bits_has_data_T_8 = req_cmd == 5'h9;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _io_resp_bits_has_data_T_9 = req_cmd == 5'hA;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _io_resp_bits_has_data_T_10 = req_cmd == 5'hB;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _io_resp_bits_has_data_T_14 = req_cmd == 5'h8;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _io_resp_bits_has_data_T_15 = req_cmd == 5'hC;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _io_resp_bits_has_data_T_16 = req_cmd == 5'hD;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _io_resp_bits_has_data_T_17 = req_cmd == 5'hE;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _io_resp_bits_has_data_T_18 = req_cmd == 5'hF;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _io_mem_access_bits_T_16 = _io_resp_bits_has_data_T_7 | _io_resp_bits_has_data_T_8 | _io_resp_bits_has_data_T_9 | _io_resp_bits_has_data_T_10 | _io_resp_bits_has_data_T_14 | _io_resp_bits_has_data_T_15 | _io_resp_bits_has_data_T_16 | _io_resp_bits_has_data_T_17 | _io_resp_bits_has_data_T_18;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:87:44, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire        _io_resp_bits_has_data_T = req_cmd == 5'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire        _io_resp_bits_has_data_T_1 = req_cmd == 5'h10;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire        _io_resp_bits_has_data_T_2 = req_cmd == 5'h6;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire        _io_resp_bits_has_data_T_3 = req_cmd == 5'h7;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :109:38, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire        _io_resp_bits_has_data_T_25 = req_cmd == 5'h15;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:92:31, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  wire        _io_mem_access_bits_T_47 = _io_resp_bits_has_data_T | _io_resp_bits_has_data_T_1 | _io_resp_bits_has_data_T_2 | _io_resp_bits_has_data_T_3 | _io_resp_bits_has_data_T_7 | _io_resp_bits_has_data_T_8 | _io_resp_bits_has_data_T_9 | _io_resp_bits_has_data_T_10 | _io_resp_bits_has_data_T_14 | _io_resp_bits_has_data_T_15 | _io_resp_bits_has_data_T_16 | _io_resp_bits_has_data_T_17 | _io_resp_bits_has_data_T_18 | _io_resp_bits_has_data_T_25 | req_cmd == 5'h2 | req_cmd == 5'h3;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:88:{35,52}, :92:31, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :112:74, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire        _GEN_0 = ~_io_mem_access_bits_T_16 | _atomics_T_16 | _atomics_T_14 | _atomics_T_12 | _atomics_T_10 | _atomics_T_8 | _atomics_T_6 | _atomics_T_4 | _atomics_T_2 | _atomics_T;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:87:44, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:112:28, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        _io_replay_next_T = state == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:76:22, :114:28, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15]
  wire [31:0] io_resp_bits_data_zeroed = req_addr[2] ? grant_word[63:32] : grant_word[31:0];	// @[generators/rocket-chip/src/main/scala/rocket/AMOALU.scala:41:{24,37,55}, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :73:23, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26]
  wire [15:0] io_resp_bits_data_zeroed_1 = req_addr[1] ? io_resp_bits_data_zeroed[31:16] : io_resp_bits_data_zeroed[15:0];	// @[generators/rocket-chip/src/main/scala/rocket/AMOALU.scala:41:{24,37,55}, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26]
  wire [7:0]  io_resp_bits_data_zeroed_2 = req_addr[0] ? io_resp_bits_data_zeroed_1[15:8] : io_resp_bits_data_zeroed_1[7:0];	// @[generators/rocket-chip/src/main/scala/rocket/AMOALU.scala:41:{24,37,55}, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26]
  wire        _GEN_1 = _io_req_ready_output & io_req_valid;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:77:26, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _GEN_2 = _io_replay_next_T & io_mem_ack_valid;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:114:28, :144:29]
  always @(posedge clock) begin
    if (_GEN_1) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
      req_addr <= io_req_bits_addr;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
      req_tag <= io_req_bits_tag;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
      req_cmd <= io_req_bits_cmd;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
      req_size <= io_req_bits_size;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
      req_signed <= io_req_bits_signed;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
      req_dprv <= io_req_bits_dprv;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
      req_dv <= io_req_bits_dv;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
      req_isLookup <= io_req_bits_isLookup;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
      req_data <= io_req_bits_data;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
      req_mask <= io_req_bits_mask;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
    end
    if (_GEN_2 & (_io_resp_bits_has_data_T | _io_resp_bits_has_data_T_1 | _io_resp_bits_has_data_T_2 | _io_resp_bits_has_data_T_3 | _io_resp_bits_has_data_T_7 | _io_resp_bits_has_data_T_8 | _io_resp_bits_has_data_T_9 | _io_resp_bits_has_data_T_10 | _io_resp_bits_has_data_T_14 | _io_resp_bits_has_data_T_15 | _io_resp_bits_has_data_T_16 | _io_resp_bits_has_data_T_17 | _io_resp_bits_has_data_T_18 | _io_resp_bits_has_data_T_25))	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:89:82, :92:31, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:73:23, :144:{29,50}, :146:28, :147:18, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
      grant_word <= io_mem_ack_bits_data;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:73:23]
    if (reset)
      state <= 2'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:76:22]
    else if (io_resp_ready & (&state))	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:76:22, :115:27, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      state <= 2'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:76:22]
    else if (_GEN_2)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:144:29]
      state <= 2'h3;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:76:22, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
    else if (io_mem_access_ready & _io_mem_access_valid_output)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:111:33, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      state <= 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:76:22, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15]
    else if (_GEN_1)	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
      state <= 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:76:22, :111:33]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:6];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        req_addr = {_RANDOM[3'h0], _RANDOM[3'h1][7:0]};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
        req_tag = _RANDOM[3'h1][14:8];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
        req_cmd = _RANDOM[3'h1][19:15];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
        req_size = _RANDOM[3'h1][21:20];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
        req_signed = _RANDOM[3'h1][22];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
        req_dprv = _RANDOM[3'h1][24:23];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
        req_dv = _RANDOM[3'h1][25];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
        req_isLookup = _RANDOM[3'h1][26];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
        req_data = {_RANDOM[3'h1][31:30], _RANDOM[3'h2], _RANDOM[3'h3][29:0]};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
        req_mask = {_RANDOM[3'h3][31:30], _RANDOM[3'h4][5:0]};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
        grant_word = {_RANDOM[3'h4][31:6], _RANDOM[3'h5], _RANDOM[3'h6][5:0]};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :73:23]
        state = _RANDOM[3'h6][7:6];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:73:23, :76:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_req_ready = _io_req_ready_output;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:77:26]
  assign io_resp_valid = &state;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:76:22, :115:27]
  assign io_resp_bits_addr = req_addr;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  assign io_resp_bits_tag = req_tag;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  assign io_resp_bits_cmd = req_cmd;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  assign io_resp_bits_size = req_size;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  assign io_resp_bits_signed = req_signed;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  assign io_resp_bits_dprv = req_dprv;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  assign io_resp_bits_dv = req_dv;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  assign io_resp_bits_isLookup = req_isLookup;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  assign io_resp_bits_data = {req_size == 2'h0 ? {56{req_signed & io_resp_bits_data_zeroed_2[7]}} : {req_size == 2'h1 ? {48{req_signed & io_resp_bits_data_zeroed_1[15]}} : {req_size == 2'h2 ? {32{req_signed & io_resp_bits_data_zeroed[31]}} : grant_word[63:32], io_resp_bits_data_zeroed[31:16]}, io_resp_bits_data_zeroed_1[15:8]}, io_resp_bits_data_zeroed_2};	// @[generators/rocket-chip/src/main/scala/rocket/AMOALU.scala:41:{24,37}, :44:{16,20,26,49,72,81,94}, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :73:23, :76:22, :111:33, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:519:15]
  assign io_resp_bits_mask = req_mask;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  assign io_resp_bits_has_data = _io_resp_bits_has_data_T | _io_resp_bits_has_data_T_1 | _io_resp_bits_has_data_T_2 | _io_resp_bits_has_data_T_3 | _io_resp_bits_has_data_T_7 | _io_resp_bits_has_data_T_8 | _io_resp_bits_has_data_T_9 | _io_resp_bits_has_data_T_10 | _io_resp_bits_has_data_T_14 | _io_resp_bits_has_data_T_15 | _io_resp_bits_has_data_T_16 | _io_resp_bits_has_data_T_17 | _io_resp_bits_has_data_T_18 | _io_resp_bits_has_data_T_25;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:89:82, :92:31, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  assign io_resp_bits_store_data = req_data;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16]
  assign io_mem_access_valid = _io_mem_access_valid_output;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:111:33]
  assign io_mem_access_bits_opcode = _io_mem_access_bits_T_16 ? (_atomics_T_16 | _atomics_T_14 | _atomics_T_12 | _atomics_T_10 | _atomics_T_8 ? 3'h2 : _GEN ? 3'h3 : 3'h0) : {_io_mem_access_bits_T_47, 2'h0};	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:87:44, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:76:22, :112:{28,57,74}, src/main/scala/chisel3/util/Mux.scala:77:13]
  assign io_mem_access_bits_param = _io_mem_access_bits_T_16 ? (_atomics_T_16 ? 3'h3 : _atomics_T_14 ? 3'h2 : _atomics_T_12 ? 3'h1 : _atomics_T_10 ? 3'h0 : _atomics_T_8 ? 3'h4 : _atomics_T_6 ? 3'h2 : _atomics_T_4 ? 3'h1 : _atomics_T_2 | ~_atomics_T ? 3'h0 : 3'h3) : 3'h0;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:87:44, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:112:28, src/main/scala/chisel3/util/Mux.scala:77:13]
  assign io_mem_access_bits_size = _GEN_0 ? {2'h0, req_size} : 4'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :76:22, :94:38, :112:28, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:464:15]
  assign io_mem_access_bits_source = _io_mem_access_bits_T_16 ? {_atomics_T_16 | _atomics_T_14 | _atomics_T_12 | _atomics_T_10 | _atomics_T_8 | _GEN, 2'h0} : 3'h4;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:87:44, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:76:22, :112:28, src/main/scala/chisel3/util/Mux.scala:77:13]
  assign io_mem_access_bits_address = _GEN_0 ? req_addr[31:0] : 32'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :94:38, :112:28, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:466:15]
  assign io_mem_access_bits_mask = _io_mem_access_bits_T_16 ? atomics_mask : _io_mem_access_bits_T_47 ? {get_a_mask_acc_5 | get_a_mask_eq_5 & req_addr[0], get_a_mask_acc_5 | get_a_mask_eq_5 & ~(req_addr[0]), get_a_mask_acc_4 | get_a_mask_eq_4 & req_addr[0], get_a_mask_acc_4 | get_a_mask_eq_4 & ~(req_addr[0]), get_a_mask_acc_3 | get_a_mask_eq_3 & req_addr[0], get_a_mask_acc_3 | get_a_mask_eq_3 & ~(req_addr[0]), get_a_mask_acc_2 | get_a_mask_eq_2 & req_addr[0], get_a_mask_acc_2 | get_a_mask_eq_2 & ~(req_addr[0])} : {put_a_mask_acc_5 | put_a_mask_eq_5 & req_addr[0], put_a_mask_acc_5 | put_a_mask_eq_5 & ~(req_addr[0]), put_a_mask_acc_4 | put_a_mask_eq_4 & req_addr[0], put_a_mask_acc_4 | put_a_mask_eq_4 & ~(req_addr[0]), put_a_mask_acc_3 | put_a_mask_eq_3 & req_addr[0], put_a_mask_acc_3 | put_a_mask_eq_3 & ~(req_addr[0]), put_a_mask_acc_2 | put_a_mask_eq_2 & req_addr[0], put_a_mask_acc_2 | put_a_mask_eq_2 & ~(req_addr[0])};	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:87:44, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :112:{28,57,74}, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27, :215:29, :222:10, src/main/scala/chisel3/util/Mux.scala:77:13]
  assign io_mem_access_bits_data = _io_mem_access_bits_T_16 ? (_atomics_T_16 | _atomics_T_14 | _atomics_T_12 | _atomics_T_10 | _atomics_T_8 | _atomics_T_6 | _atomics_T_4 | _atomics_T_2 | _atomics_T ? req_data : 64'h0) : _io_mem_access_bits_T_47 ? 64'h0 : req_data;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:87:44, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :112:{28,57,74}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:470:15, src/main/scala/chisel3/util/Mux.scala:77:13]
  assign io_replay_next = _io_replay_next_T | (&state) & ~io_resp_ready & ~req_isLookup;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:72:16, :76:22, :114:{28,43,64,80,83}, :115:27]
endmodule

