// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ProbeUnit(
  input         clock,
                reset,
  output        io_req_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  input         io_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  input  [1:0]  io_req_bits_param,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  input  [3:0]  io_req_bits_size,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  input  [2:0]  io_req_bits_source,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  input  [31:0] io_req_bits_address,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  input         io_rep_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output        io_rep_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [2:0]  io_rep_bits_param,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [3:0]  io_rep_bits_size,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [2:0]  io_rep_bits_source,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [31:0] io_rep_bits_address,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  input         io_meta_read_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output        io_meta_read_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [5:0]  io_meta_read_bits_idx,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [19:0] io_meta_read_bits_tag,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  input         io_meta_write_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output        io_meta_write_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [5:0]  io_meta_write_bits_idx,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [15:0] io_meta_write_bits_way_en,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [1:0]  io_meta_write_bits_data_coh_state,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [19:0] io_meta_write_bits_data_tag,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  input         io_wb_req_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output        io_wb_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [19:0] io_wb_req_bits_tag,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [5:0]  io_wb_req_bits_idx,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [2:0]  io_wb_req_bits_source,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
                io_wb_req_bits_param,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  output [15:0] io_wb_req_bits_way_en,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  input  [15:0] io_way_en,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  input         io_mshr_rdy,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
  input  [1:0]  io_block_state_state	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:609:14]
);

  reg  [3:0]  state;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22]
  reg  [1:0]  req_param;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16]
  reg  [3:0]  req_size;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16]
  reg  [2:0]  req_source;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16]
  reg  [31:0] req_address;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16]
  reg  [15:0] way_en;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:629:19]
  reg  [1:0]  old_coh_state;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:631:20]
  wire [3:0]  _GEN = {req_param, (|way_en) ? old_coh_state : 2'h0};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16, :629:19, :630:28, :631:20, :633:22, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, :161:16]
  wire        _GEN_0 = _GEN == 4'hB;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, :130:10, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_1 = _GEN == 4'h4;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:683:17, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_2 = _GEN == 4'h5;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:637:25, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_3 = _GEN == 4'h6;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:655:28, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_4 = _GEN == 4'h7;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:696:11, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_5 = _GEN == 4'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_6 = _GEN == 4'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:643:31, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_7 = _GEN == 4'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:671:11, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_8 = _GEN == 4'h3;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:676:11, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_9 = _GEN_8 | _GEN_7;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:38:36, :56:20]
  wire [2:0]  io_rep_bits_c_param = _GEN_9 ? 3'h3 : _GEN_6 ? 3'h4 : _GEN_5 ? 3'h5 : _GEN_4 | _GEN_3 ? 3'h0 : _GEN_2 ? 3'h4 : _GEN_1 ? 3'h5 : _GEN_0 | _GEN == 4'hA ? 3'h1 : _GEN == 4'h9 ? 3'h2 : _GEN == 4'h8 ? 3'h5 : 3'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:648:32, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, :131:10, :132:10, generators/rocket-chip/src/main/scala/util/Misc.scala:38:36, :56:20]
  wire        _io_req_ready_output = state == 4'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :636:25]
  wire        _io_rep_valid_T = state == 4'h5;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :637:25]
  wire        _io_meta_read_valid_output = state == 4'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :643:31]
  wire        _io_meta_write_valid_output = state == 4'h8;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :648:32]
  wire        _io_wb_req_valid_output = state == 4'h6;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :655:28]
  wire        _GEN_10 = _io_req_ready_output & io_req_valid;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:636:25, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _GEN_11 = state == 4'h3;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :676:11, :679:15]
  always @(posedge clock) begin
    if (reset)
      state <= 4'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22]
    else if (io_meta_write_ready & _io_meta_write_valid_output)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:648:32, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      state <= 4'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22]
    else if (state == 4'h7 & io_wb_req_ready)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :696:11, :700:{15,36}]
      state <= 4'h8;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :648:32]
    else if (io_wb_req_ready & _io_wb_req_valid_output)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:655:28, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      state <= 4'h7;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :696:11]
    else if (_io_rep_valid_T & io_rep_ready)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:637:25, :690:29]
      state <= {|way_en, 3'h0};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :629:19, :630:28, :691:17]
    else if (state == 4'h4)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :683:17, :686:15]
      state <= (|way_en) & (_GEN_8 | ~(_GEN_7 | _GEN_6 | _GEN_5) & (_GEN_4 | ~(_GEN_3 | _GEN_2 | _GEN_1) & _GEN_0)) ? 4'h6 : 4'h5;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :629:19, :630:28, :637:25, :655:28, :687:{17,30}, generators/rocket-chip/src/main/scala/util/Misc.scala:38:9, :56:20]
    else if (_GEN_11)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:679:15]
      state <= io_mshr_rdy ? 4'h4 : 4'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :643:31, :683:17]
    else if (state == 4'h2)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :671:11, :675:15]
      state <= 4'h3;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :676:11]
    else if (io_meta_read_ready & _io_meta_read_valid_output)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:643:31, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      state <= 4'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :671:11]
    else if (_GEN_10)	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
      state <= 4'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :643:31]
    if (_GEN_10) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
      req_param <= io_req_bits_param;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16]
      req_size <= io_req_bits_size;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16]
      req_source <= io_req_bits_source;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16]
      req_address <= io_req_bits_address;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16]
    end
    if (_GEN_11) begin	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:679:15]
      way_en <= io_way_en;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:629:19]
      old_coh_state <= io_block_state_state;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:631:20]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:4];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        state = _RANDOM[3'h0][3:0];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22]
        req_param = _RANDOM[3'h0][8:7];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :625:16]
        req_size = _RANDOM[3'h0][12:9];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :625:16]
        req_source = _RANDOM[3'h0][15:13];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :625:16]
        req_address = {_RANDOM[3'h0][31:16], _RANDOM[3'h1][15:0]};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:623:22, :625:16]
        way_en = {_RANDOM[3'h3][31:25], _RANDOM[3'h4][8:0]};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:629:19]
        old_coh_state = _RANDOM[3'h4][10:9];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:629:19, :631:20]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_req_ready = _io_req_ready_output;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:636:25]
  assign io_rep_valid = _io_rep_valid_T;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:637:25]
  assign io_rep_bits_param = io_rep_bits_c_param;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:38:36]
  assign io_rep_bits_size = req_size;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16]
  assign io_rep_bits_source = req_source;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16]
  assign io_rep_bits_address = req_address;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16]
  assign io_meta_read_valid = _io_meta_read_valid_output;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:643:31]
  assign io_meta_read_bits_idx = req_address[11:6];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16, :626:28]
  assign io_meta_read_bits_tag = req_address[31:12];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16, :627:29]
  assign io_meta_write_valid = _io_meta_write_valid_output;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:648:32]
  assign io_meta_write_bits_idx = req_address[11:6];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16, :626:28]
  assign io_meta_write_bits_way_en = way_en;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:629:19]
  assign io_meta_write_bits_data_coh_state = _GEN_9 ? 2'h2 : _GEN_6 ? 2'h1 : _GEN_5 ? 2'h0 : {1'h0, _GEN_4 | _GEN_3 | _GEN_2};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:123:10, :124:10, :161:16, generators/rocket-chip/src/main/scala/util/Misc.scala:38:{36,63}, :56:20]
  assign io_meta_write_bits_data_tag = req_address[31:12];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16, :627:29]
  assign io_wb_req_valid = _io_wb_req_valid_output;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:655:28]
  assign io_wb_req_bits_tag = req_address[31:12];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16, :627:29]
  assign io_wb_req_bits_idx = req_address[11:6];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16, :626:28]
  assign io_wb_req_bits_source = req_source;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:625:16]
  assign io_wb_req_bits_param = io_rep_bits_c_param;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:38:36]
  assign io_wb_req_bits_way_en = way_en;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:629:19]
endmodule

