// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module BuffedALUBC(
  input         clock,
                reset,
                io_lookup_req_valid,	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:734:14]
  output        io_lookup_req_ready,	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:734:14]
  input  [39:0] io_lookup_req_paddr,	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:734:14]
  output        io_lookup_resp_valid,	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:734:14]
  output [7:0]  io_lookup_resp_atom_id,	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:734:14]
  output        io_lookup_resp_xcpt,	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:734:14]
  input  [31:0] io_acrbase,	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:734:14]
  input  [39:0] io_map_update_addr,	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:734:14]
  input         io_map_update_valid,	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:734:14]
  input  [7:0]  io_map_update_id	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:734:14]
);

  wire        _block_queue_T_8;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:813:38]
  wire        _alb_io_resp_miss;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:754:23]
  wire [7:0]  _alb_io_resp_atom_id;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:754:23]
  reg  [39:0] s1_addr;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:763:24]
  reg  [39:0] s2_addr;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:764:24]
  reg         s1_valid;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:767:28]
  wire        s0_valid = io_lookup_req_valid & (|io_acrbase);	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:780:{48,64}]
  wire        _io_lookup_req_ready_output = ~s1_valid & ~_block_queue_T_8 & ~io_map_update_valid;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:767:28, :783:{56,71,122}, :785:70, :813:38]
  assign _block_queue_T_8 = s1_valid & s1_addr[39:20] == io_lookup_req_paddr[39:20];	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:763:24, :767:28, :793:55, :795:55, :812:100, :813:{38,73}]
  reg         io_lookup_resp_valid_REG;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:832:37]
  reg  [7:0]  io_lookup_resp_atom_id_REG;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:834:63]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:841:11]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:841:11]
      if ((`PRINTF_COND_) & ~reset) begin	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:841:11, :845:11]
        $fwrite(32'h80000002, "S0- V:%d PA:0x%x ALBMiss: %d\n", s0_valid, io_lookup_req_paddr, _alb_io_resp_miss);	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:754:23, :780:48, :841:11]
        $fwrite(32'h80000002, "S1- V:%d PA:0x%x MemAddr: 0x%x ADV:%d\n", s1_valid, s1_addr, {7'h0, {13'h0, s1_addr[39:20]} + {1'h0, io_acrbase}}, 1'h0);	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:763:24, :767:28, :793:55, :795:55, :796:79, :814:38, :841:11, :842:11]
        $fwrite(32'h80000002, "S2- V:%d PA:0x%x\n", 1'h0, s2_addr);	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:764:24, :814:38, :841:11, :843:11]
        $fwrite(32'h80000002, "S3- V:%d PA:0x%x xcpt:%d nack:%d ADV:%d\n", 1'h0, 40'h0, 1'h0, 1'h0, 1'h0);	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:765:24, :814:38, :841:11, :844:11]
        $fwrite(32'h80000002, "S4- V:%d PA:0x%x AID: %d\n", 1'h0, 40'h0, 8'h0);	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:734:14, :754:23, :765:24, :811:48, :814:38, :841:11, :845:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin
    if (s1_valid) begin	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:767:28]
    end
    else	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:767:28]
      s1_addr <= io_lookup_req_paddr;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:763:24]
    s2_addr <= s1_addr;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:763:24, :764:24]
    io_lookup_resp_valid_REG <= s0_valid & _io_lookup_req_ready_output & ~_alb_io_resp_miss;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:754:23, :780:48, :785:70, :832:{37,70,73}]
    io_lookup_resp_atom_id_REG <= _alb_io_resp_atom_id;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:754:23, :834:63]
    if (reset)
      s1_valid <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:767:28, :814:38]
    else if (s1_valid) begin	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:767:28]
    end
    else	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:767:28]
      s1_valid <= s0_valid & _alb_io_resp_miss;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:754:23, :767:28, :780:48, :790:66]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:4];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        s1_addr = {_RANDOM[3'h0], _RANDOM[3'h1][7:0]};	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:763:24]
        s2_addr = {_RANDOM[3'h1][31:8], _RANDOM[3'h2][15:0]};	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:763:24, :764:24]
        s1_valid = _RANDOM[3'h3][24];	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:767:28]
        io_lookup_resp_valid_REG = _RANDOM[3'h3][28];	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:767:28, :832:37]
        io_lookup_resp_atom_id_REG = {_RANDOM[3'h3][31:29], _RANDOM[3'h4][4:0]};	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:767:28, :834:63]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Buffed_ALB_FA alb (	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:754:23]
    .clock               (clock),
    .reset               (reset),
    .io_req_rden         (s0_valid & ~s1_valid & ~_block_queue_T_8 & ~io_map_update_valid),	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:767:28, :780:48, :783:{56,71,119,122}, :813:38]
    .io_req_paddr_rd     (io_lookup_req_paddr),
    .io_req_paddr_wr     (40'h0),	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:765:24]
    .io_resp_miss        (_alb_io_resp_miss),
    .io_resp_atom_id     (_alb_io_resp_atom_id),
    .io_map_update_addr  (io_map_update_addr),
    .io_map_update_valid (io_map_update_valid),
    .io_map_update_id    (io_map_update_id)
  );
  assign io_lookup_req_ready = _io_lookup_req_ready_output;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:785:70]
  assign io_lookup_resp_valid = io_lookup_resp_valid_REG;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:832:37]
  assign io_lookup_resp_atom_id = io_lookup_resp_atom_id_REG;	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:834:63]
  assign io_lookup_resp_xcpt = ~(|io_acrbase);	// @[generators/rocket-chip/src/main/scala/tile/BoundsChecker.scala:780:64, :835:68]
endmodule

