// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TLMonitor_27(
  input        clock,
               reset,
               io_in_a_ready,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
               io_in_a_valid,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [2:0]  io_in_a_bits_opcode,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
               io_in_a_bits_param,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
               io_in_a_bits_size,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [9:0]  io_in_a_bits_source,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [16:0] io_in_a_bits_address,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [7:0]  io_in_a_bits_mask,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input        io_in_a_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
               io_in_d_ready,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
               io_in_d_valid,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [2:0]  io_in_d_bits_size,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [9:0]  io_in_d_bits_source	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
);

  wire [31:0]   _plusarg_reader_out;	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire          a_first_done = io_in_a_ready & io_in_a_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg  [2:0]    a_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  reg  [2:0]    opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:384:22]
  reg  [2:0]    param;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:385:22]
  reg  [2:0]    size;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:386:22]
  reg  [9:0]    source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:387:22]
  reg  [16:0]   address;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
  reg  [2:0]    d_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  reg  [2:0]    size_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22]
  reg  [9:0]    source_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:538:22]
  reg  [512:0]  inflight;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27]
  reg  [2051:0] inflight_opcodes;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35]
  reg  [2051:0] inflight_sizes;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:615:33]
  reg  [2:0]    a_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  wire          a_first_1 = a_first_counter_1 == 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/util/Misc.scala:202:34]
  reg  [2:0]    d_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  wire          d_first_1 = d_first_counter_1 == 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/util/Misc.scala:202:34]
  wire          _GEN = a_first_done & a_first_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:652:25, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg  [31:0]   watchdog;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    wire [7:0][2:0] _GEN_0 = '{3'h4, 3'h5, 3'h2, 3'h1, 3'h1, 3'h1, 3'h0, 3'h0};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:686:39]
    wire [7:0][2:0] _GEN_1 = '{3'h4, 3'h4, 3'h2, 3'h1, 3'h1, 3'h1, 3'h0, 3'h0};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:685:38]
    wire            _source_ok_WIRE_1 = io_in_a_bits_source == 10'h100;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9]
    wire            _source_ok_WIRE_2 = io_in_a_bits_source == 10'h101;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9]
    wire            _source_ok_WIRE_3 = io_in_a_bits_source == 10'h102;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9]
    wire            _source_ok_WIRE_4 = io_in_a_bits_source == 10'h200;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9]
    wire            source_ok = ~(|(io_in_a_bits_source[9:8])) | _source_ok_WIRE_1 | _source_ok_WIRE_2 | _source_ok_WIRE_3 | _source_ok_WIRE_4;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, :54:{10,32}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1126:46]
    wire [12:0]     _is_aligned_mask_T_1 = 13'h3F << io_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:235:71]
    wire [5:0]      _GEN_2 = io_in_a_bits_address[5:0] & ~(_is_aligned_mask_T_1[5:0]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:16, generators/rocket-chip/src/main/scala/util/package.scala:235:{46,71,76}]
    wire            _mask_T = io_in_a_bits_size > 3'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:640:42, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
    wire            mask_size = io_in_a_bits_size[1:0] == 2'h2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, src/main/scala/chisel3/util/OneHot.scala:64:49, :65:12]
    wire            mask_acc = _mask_T | mask_size & ~(io_in_a_bits_address[2]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
    wire            mask_acc_1 = _mask_T | mask_size & io_in_a_bits_address[2];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
    wire            mask_size_1 = io_in_a_bits_size[1:0] == 2'h1;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, src/main/scala/chisel3/util/OneHot.scala:64:49, :65:12]
    wire            mask_eq_2 = ~(io_in_a_bits_address[2]) & ~(io_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
    wire            mask_acc_2 = mask_acc | mask_size_1 & mask_eq_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
    wire            mask_eq_3 = ~(io_in_a_bits_address[2]) & io_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
    wire            mask_acc_3 = mask_acc | mask_size_1 & mask_eq_3;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
    wire            mask_eq_4 = io_in_a_bits_address[2] & ~(io_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
    wire            mask_acc_4 = mask_acc_1 | mask_size_1 & mask_eq_4;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
    wire            mask_eq_5 = io_in_a_bits_address[2] & io_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
    wire            mask_acc_5 = mask_acc_1 | mask_size_1 & mask_eq_5;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
    wire [7:0]      mask = {mask_acc_5 | mask_eq_5 & io_in_a_bits_address[0], mask_acc_5 | mask_eq_5 & ~(io_in_a_bits_address[0]), mask_acc_4 | mask_eq_4 & io_in_a_bits_address[0], mask_acc_4 | mask_eq_4 & ~(io_in_a_bits_address[0]), mask_acc_3 | mask_eq_3 & io_in_a_bits_address[0], mask_acc_3 | mask_eq_3 & ~(io_in_a_bits_address[0]), mask_acc_2 | mask_eq_2 & io_in_a_bits_address[0], mask_acc_2 | mask_eq_2 & ~(io_in_a_bits_address[0])};	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27, :215:29, :222:10]
    wire            _GEN_3 = io_in_a_valid & io_in_a_bits_opcode == 3'h6 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :81:25]
    wire            _GEN_4 = _source_ok_WIRE_1 & io_in_a_bits_size == 3'h6 & io_in_a_bits_address[16];	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, :91:44, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :81:25, :83:78]
    wire            _GEN_5 = io_in_a_bits_param > 3'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:640:42]
    wire            _GEN_6 = io_in_a_bits_mask != 8'hFF;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:88:{18,31}]
    wire            _GEN_7 = io_in_a_valid & (&io_in_a_bits_opcode) & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :92:25]
    wire            _GEN_8 = io_in_a_valid & io_in_a_bits_opcode == 3'h4 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :104:25]
    wire            _GEN_9 = io_in_a_bits_mask != mask;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:110:30, generators/rocket-chip/src/main/scala/util/Misc.scala:222:10]
    wire            _GEN_10 = io_in_a_valid & io_in_a_bits_opcode == 3'h0 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :114:25, generators/rocket-chip/src/main/scala/util/Misc.scala:202:34]
    wire            _GEN_11 = io_in_a_valid & io_in_a_bits_opcode == 3'h1 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :122:25]
    wire            _GEN_12 = io_in_a_valid & io_in_a_bits_opcode == 3'h2 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :130:25, :640:42]
    wire            _GEN_13 = io_in_a_valid & io_in_a_bits_opcode == 3'h3 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:148:30, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :138:25]
    wire            _GEN_14 = io_in_a_valid & io_in_a_bits_opcode == 3'h5 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :146:25]
    wire            _GEN_15 = io_in_a_valid & (|a_first_counter) & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    wire            _GEN_16 = io_in_d_valid & (|d_first_counter) & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
    wire [2051:0]   _GEN_17 = {2040'h0, io_in_d_bits_source, 2'h0};	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:54:32, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:634:44]
    wire [2051:0]   _a_opcode_lookup_T_1 = inflight_opcodes >> _GEN_17;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :634:44]
    wire            _GEN_18 = io_in_d_valid & d_first_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:671:26]
    wire            same_cycle_resp = io_in_a_valid & a_first_1 & io_in_a_bits_source == io_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:681:{88,113}]
    wire            _GEN_19 = _GEN_18 & same_cycle_resp & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :671:26, :681:88]
    wire            _GEN_20 = _GEN_18 & ~same_cycle_resp & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :671:26, :681:88, :684:30]
    wire [512:0]    _GEN_21 = inflight >> io_in_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27, :658:26]
    wire [512:0]    _GEN_22 = inflight >> io_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27, :682:25]
    wire [2051:0]   _a_size_lookup_T_1 = inflight_sizes >> _GEN_17;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:615:33, :634:44, :638:40]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if (_GEN_3) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries AcquireBlock type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_3 & ~_GEN_4) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :83:78]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries AcquireBlock from a client which does not support Probe (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_3 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1126:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquireBlock carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_3 & ~_mask_T) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquireBlock smaller than a beat (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_3 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquireBlock address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_3 & _GEN_5) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquireBlock carries invalid grow param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_3 & _GEN_6) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :88:31]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquireBlock contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_3 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquireBlock is corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_7) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries AcquirePerm type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_7 & ~_GEN_4) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :83:78]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries AcquirePerm from a client which does not support Probe (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_7 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1126:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_7 & ~_mask_T) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm smaller than a beat (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_7 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_7 & _GEN_5) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm carries invalid grow param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_7 & ~(|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :99:31]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm requests NtoB (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_7 & _GEN_6) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :88:31]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_7 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm is corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_8 & ~(~(|(io_in_a_bits_source[9:8])) | _source_ok_WIRE_1 | _source_ok_WIRE_2 | _source_ok_WIRE_3 | _source_ok_WIRE_4)) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, :54:{10,32}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1162:43]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries Get type which master claims it can't emit (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_8 & ~(io_in_a_bits_size != 3'h7 & io_in_a_bits_address[16])) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:92:38, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :92:25, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:671:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries Get type which slave claims it can't support (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_8 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1126:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Get carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_8 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Get address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_8 & (|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :99:31]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Get carries invalid param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_8 & _GEN_9) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :110:30]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Get contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_8 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Get is corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_10) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries PutFull type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_10 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1126:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutFull carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_10 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutFull address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_10 & (|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :99:31]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutFull carries invalid param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_10 & _GEN_9) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :110:30]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutFull contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_11) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries PutPartial type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_11 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1126:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutPartial carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_11 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutPartial address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_11 & (|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :99:31]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutPartial carries invalid param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_11 & (|(io_in_a_bits_mask & ~mask))) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :127:{31,33,40}, generators/rocket-chip/src/main/scala/util/Misc.scala:222:10]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutPartial contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_12) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries Arithmetic type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_12 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1126:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Arithmetic carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_12 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Arithmetic address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_12 & io_in_a_bits_param > 3'h4) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:141:33, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :104:25]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Arithmetic carries invalid opcode param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_12 & _GEN_9) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :110:30]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Arithmetic contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_13) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries Logical type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_13 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1126:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Logical carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_13 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Logical address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_13 & io_in_a_bits_param[2]) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:148:30, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Logical carries invalid opcode param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_13 & _GEN_9) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :110:30]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Logical contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_14) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries Hint type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_14 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1126:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Hint carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_14 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Hint address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_14 & (|(io_in_a_bits_param[2:1]))) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:161:28, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Hint carries invalid opcode param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_14 & _GEN_9) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :110:30]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Hint contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_14 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Hint is corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (io_in_d_valid & ~reset & ~(io_in_d_bits_source[9:8] == 2'h0 | io_in_d_bits_source == 10'h100 | io_in_d_bits_source == 10'h101 | io_in_d_bits_source == 10'h102 | io_in_d_bits_source == 10'h200)) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, :54:{10,32}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1126:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel AccessAckData carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      end
      if (_GEN_15 & io_in_a_bits_opcode != opcode) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :384:22, :390:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel opcode changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_15 & io_in_a_bits_param != param) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :385:22, :391:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel param changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_15 & io_in_a_bits_size != size) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :386:22, :392:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel size changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_15 & io_in_a_bits_source != source) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :387:22, :393:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel source changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_15 & io_in_a_bits_address != address) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :388:22, :394:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel address changed with multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_16 & io_in_d_bits_size != size_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :537:22, :544:29]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel size changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      end
      if (_GEN_16 & io_in_d_bits_source != source_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :538:22, :545:29]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel source changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      end
      if (_GEN & ~reset & _GEN_21[0]) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :652:25, :658:26]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel re-used a source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if (_GEN_18 & ~reset & ~(_GEN_22[0] | same_cycle_resp)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :671:26, :681:88, :682:{25,49}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel acknowledged for nothing inflight (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      end
      if (_GEN_19 & ~(_GEN_1[io_in_a_bits_opcode] == 3'h1 | _GEN_0[io_in_a_bits_opcode] == 3'h1)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :49:11, :685:{38,77}, :686:39]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel contains improper opcode response (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      end
      if (_GEN_19 & io_in_a_bits_size != io_in_d_bits_size) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :687:36]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel contains improper response size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      end
      if (_GEN_20 & ~(_GEN_1[_a_opcode_lookup_T_1[3:1]] == 3'h1 | _GEN_0[_a_opcode_lookup_T_1[3:1]] == 3'h1)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :49:11, :634:{44,152}, :685:38, :686:39, :689:{38,72}, :690:38]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel contains improper opcode response (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      end
      if (_GEN_20 & io_in_d_bits_size != _a_size_lookup_T_1[3:1]) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :638:{40,144}, :691:36]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel contains improper response size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      end
      if (_GEN_18 & a_first_1 & io_in_a_valid & io_in_a_bits_source == io_in_d_bits_source & ~reset & ~(~io_in_d_ready | io_in_a_ready)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :671:26, :694:90, :695:{15,32}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $error("Assertion failed: ready check\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      end
      if (~reset & ~(inflight == 513'h0 | _plusarg_reader_out == 32'h0 | watchdog < _plusarg_reader_out)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :611:27, :706:27, :709:{26,39,47,59}, generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $error("Assertion failed: TileLink timeout expired (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:84:68)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [12:0]   _GEN_23 = {10'h0, io_in_d_bits_size};	// @[generators/rocket-chip/src/main/scala/util/package.scala:235:71]
  wire [12:0]   _d_first_beats1_decode_T_1 = 13'h3F << _GEN_23;	// @[generators/rocket-chip/src/main/scala/util/package.scala:235:71]
  wire [12:0]   _d_first_beats1_decode_T_5 = 13'h3F << _GEN_23;	// @[generators/rocket-chip/src/main/scala/util/package.scala:235:71]
  wire [8194:0] _GEN_24 = {8183'h0, io_in_a_bits_source, 2'h0};	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:54:32, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:656:54]
  wire [8206:0] _GEN_25 = {8195'h0, io_in_d_bits_source, 2'h0};	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:54:32, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:677:76]
  wire [1023:0] _d_clr_T = 1024'h1 << io_in_d_bits_source;	// @[src/main/scala/chisel3/util/OneHot.scala:58:35]
  wire [1023:0] _a_set_T = 1024'h1 << io_in_a_bits_source;	// @[src/main/scala/chisel3/util/OneHot.scala:58:35]
  wire [8206:0] _d_opcodes_clr_T_5 = 8207'hF << _GEN_25;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:677:76]
  wire [8194:0] _a_opcodes_set_T_1 = {8191'h0, _GEN ? {io_in_a_bits_opcode, 1'h1} : 4'h0} << _GEN_24;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:632:35, :643:40, :652:{25,70}, :654:{28,61}, :656:54, :818:47]
  wire [8206:0] _d_sizes_clr_T_5 = 8207'hF << _GEN_25;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:677:76, :678:74]
  wire [8194:0] _a_sizes_set_T_1 = {8191'h0, _GEN ? {io_in_a_bits_size, 1'h1} : 4'h0} << _GEN_24;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:632:35, :645:38, :652:{25,70}, :655:{28,59}, :656:54, :657:52, :818:47]
  wire          _d_first_T_2 = io_in_d_ready & io_in_d_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire          _GEN_26 = _d_first_T_2 & d_first_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:675:25, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  always @(posedge clock) begin
    if (reset) begin
      a_first_counter <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/util/Misc.scala:202:34]
      d_first_counter <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/util/Misc.scala:202:34]
      inflight <= 513'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27]
      inflight_opcodes <= 2052'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35]
      inflight_sizes <= 2052'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :615:33]
      a_first_counter_1 <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/util/Misc.scala:202:34]
      d_first_counter_1 <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/util/Misc.scala:202:34]
      watchdog <= 32'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27]
    end
    else begin
      if (a_first_done) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
        if (|a_first_counter)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25]
          a_first_counter <= a_first_counter - 3'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28]
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          a_first_counter <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/util/Misc.scala:202:34]
        if (a_first_1)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          a_first_counter_1 <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/util/Misc.scala:202:34]
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          a_first_counter_1 <= a_first_counter_1 - 3'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28]
      end
      if (_d_first_T_2) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
        if (|d_first_counter)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25]
          d_first_counter <= d_first_counter - 3'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28]
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          d_first_counter <= ~(_d_first_beats1_decode_T_1[5:3]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/util/package.scala:235:{46,71,76}]
        if (d_first_1)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          d_first_counter_1 <= ~(_d_first_beats1_decode_T_5[5:3]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/util/package.scala:235:{46,71,76}]
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          d_first_counter_1 <= d_first_counter_1 - 3'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28]
      end
      inflight <= (inflight | (_GEN ? _a_set_T[512:0] : 513'h0)) & ~(_GEN_26 ? _d_clr_T[512:0] : 513'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27, :623:34, :652:{25,70}, :653:28, :661:34, :675:{25,89}, :676:21, :702:{27,36,38}, src/main/scala/chisel3/util/OneHot.scala:58:35]
      inflight_opcodes <= (inflight_opcodes | (_GEN ? _a_opcodes_set_T_1[2051:0] : 2052'h0)) & ~(_GEN_26 ? _d_opcodes_clr_T_5[2051:0] : 2052'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :627:33, :652:{25,70}, :656:{28,54}, :665:33, :675:{25,89}, :677:{21,76}, :703:{43,60,62}]
      inflight_sizes <= (inflight_sizes | (_GEN ? _a_sizes_set_T_1[2051:0] : 2052'h0)) & ~(_GEN_26 ? _d_sizes_clr_T_5[2051:0] : 2052'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :615:33, :629:31, :652:{25,70}, :657:{28,52}, :667:31, :675:{25,89}, :678:{21,74}, :704:{39,54,56}]
      if (a_first_done | _d_first_T_2)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:712:25, src/main/scala/chisel3/util/Decoupled.scala:52:35]
        watchdog <= 32'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27]
      else	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:712:25]
        watchdog <= watchdog + 32'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27, :711:26]
    end
    if (a_first_done & ~(|a_first_counter)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:396:18, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      opcode <= io_in_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:384:22]
      param <= io_in_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:385:22]
      size <= io_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:386:22]
      source <= io_in_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:387:22]
      address <= io_in_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
    end
    if (_d_first_T_2 & ~(|d_first_counter)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:549:18, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      size_1 <= io_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22]
      source_1 <= io_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:538:22]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:147];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [7:0] i = 8'h0; i < 8'h94; i += 8'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        a_first_counter = _RANDOM[8'h0][2:0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
        opcode = _RANDOM[8'h0][5:3];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:384:22]
        param = _RANDOM[8'h0][8:6];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:385:22]
        size = _RANDOM[8'h0][11:9];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:386:22]
        source = _RANDOM[8'h0][21:12];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:387:22]
        address = {_RANDOM[8'h0][31:22], _RANDOM[8'h1][6:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
        d_first_counter = _RANDOM[8'h1][9:7];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
        size_1 = _RANDOM[8'h1][17:15];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22, :537:22]
        source_1 = _RANDOM[8'h1][27:18];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22, :538:22]
        inflight = {_RANDOM[8'h1][31:30], _RANDOM[8'h2], _RANDOM[8'h3], _RANDOM[8'h4], _RANDOM[8'h5], _RANDOM[8'h6], _RANDOM[8'h7], _RANDOM[8'h8], _RANDOM[8'h9], _RANDOM[8'hA], _RANDOM[8'hB], _RANDOM[8'hC], _RANDOM[8'hD], _RANDOM[8'hE], _RANDOM[8'hF], _RANDOM[8'h10], _RANDOM[8'h11][30:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22, :611:27]
        inflight_opcodes = {_RANDOM[8'h11][31], _RANDOM[8'h12], _RANDOM[8'h13], _RANDOM[8'h14], _RANDOM[8'h15], _RANDOM[8'h16], _RANDOM[8'h17], _RANDOM[8'h18], _RANDOM[8'h19], _RANDOM[8'h1A], _RANDOM[8'h1B], _RANDOM[8'h1C], _RANDOM[8'h1D], _RANDOM[8'h1E], _RANDOM[8'h1F], _RANDOM[8'h20], _RANDOM[8'h21], _RANDOM[8'h22], _RANDOM[8'h23], _RANDOM[8'h24], _RANDOM[8'h25], _RANDOM[8'h26], _RANDOM[8'h27], _RANDOM[8'h28], _RANDOM[8'h29], _RANDOM[8'h2A], _RANDOM[8'h2B], _RANDOM[8'h2C], _RANDOM[8'h2D], _RANDOM[8'h2E], _RANDOM[8'h2F], _RANDOM[8'h30], _RANDOM[8'h31], _RANDOM[8'h32], _RANDOM[8'h33], _RANDOM[8'h34], _RANDOM[8'h35], _RANDOM[8'h36], _RANDOM[8'h37], _RANDOM[8'h38], _RANDOM[8'h39], _RANDOM[8'h3A], _RANDOM[8'h3B], _RANDOM[8'h3C], _RANDOM[8'h3D], _RANDOM[8'h3E], _RANDOM[8'h3F], _RANDOM[8'h40], _RANDOM[8'h41], _RANDOM[8'h42], _RANDOM[8'h43], _RANDOM[8'h44], _RANDOM[8'h45], _RANDOM[8'h46], _RANDOM[8'h47], _RANDOM[8'h48], _RANDOM[8'h49], _RANDOM[8'h4A], _RANDOM[8'h4B], _RANDOM[8'h4C], _RANDOM[8'h4D], _RANDOM[8'h4E], _RANDOM[8'h4F], _RANDOM[8'h50], _RANDOM[8'h51], _RANDOM[8'h52][2:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27, :613:35]
        inflight_sizes = {_RANDOM[8'h52][31:3], _RANDOM[8'h53], _RANDOM[8'h54], _RANDOM[8'h55], _RANDOM[8'h56], _RANDOM[8'h57], _RANDOM[8'h58], _RANDOM[8'h59], _RANDOM[8'h5A], _RANDOM[8'h5B], _RANDOM[8'h5C], _RANDOM[8'h5D], _RANDOM[8'h5E], _RANDOM[8'h5F], _RANDOM[8'h60], _RANDOM[8'h61], _RANDOM[8'h62], _RANDOM[8'h63], _RANDOM[8'h64], _RANDOM[8'h65], _RANDOM[8'h66], _RANDOM[8'h67], _RANDOM[8'h68], _RANDOM[8'h69], _RANDOM[8'h6A], _RANDOM[8'h6B], _RANDOM[8'h6C], _RANDOM[8'h6D], _RANDOM[8'h6E], _RANDOM[8'h6F], _RANDOM[8'h70], _RANDOM[8'h71], _RANDOM[8'h72], _RANDOM[8'h73], _RANDOM[8'h74], _RANDOM[8'h75], _RANDOM[8'h76], _RANDOM[8'h77], _RANDOM[8'h78], _RANDOM[8'h79], _RANDOM[8'h7A], _RANDOM[8'h7B], _RANDOM[8'h7C], _RANDOM[8'h7D], _RANDOM[8'h7E], _RANDOM[8'h7F], _RANDOM[8'h80], _RANDOM[8'h81], _RANDOM[8'h82], _RANDOM[8'h83], _RANDOM[8'h84], _RANDOM[8'h85], _RANDOM[8'h86], _RANDOM[8'h87], _RANDOM[8'h88], _RANDOM[8'h89], _RANDOM[8'h8A], _RANDOM[8'h8B], _RANDOM[8'h8C], _RANDOM[8'h8D], _RANDOM[8'h8E], _RANDOM[8'h8F], _RANDOM[8'h90], _RANDOM[8'h91], _RANDOM[8'h92][6:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :615:33]
        a_first_counter_1 = _RANDOM[8'h92][9:7];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:615:33]
        d_first_counter_1 = _RANDOM[8'h92][12:10];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:615:33]
        watchdog = {_RANDOM[8'h92][31:13], _RANDOM[8'h93][12:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:615:33, :706:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("tilelink_timeout=%d"),
    .WIDTH(32)
  ) plusarg_reader (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (_plusarg_reader_out)
  );
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("tilelink_timeout=%d"),
    .WIDTH(32)
  ) plusarg_reader_1 (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (/* unused */)
  );
endmodule

