// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module RequestQueue(
  input         clock,
                reset,
  output [39:0] io_deq_vaddr,	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:42:14]
  output        io_deq_valid	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:42:14]
);

  reg [4:0] head;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:59:21]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:71:13]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:71:13]
      if ((`PRINTF_COND_) & 1'h0)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:42:14, :50:18, :51:18, :64:{21,37}, :65:17, :66:17, :71:13]
        $fwrite(32'h80000002, "PRQ Enq - vaddr: 0x%x paddr: 0x%x\n", 40'h0, 40'h0);	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:42:14, :71:13]
      if ((`PRINTF_COND_) & (|head) & ~reset)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:59:21, :71:13, :80:24, :85:13]
        $fwrite(32'h80000002, "PRQ Deq - vaddr: 0x%x paddr: 0x%x\n", 40'h0, 40'h0);	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:42:14, :71:13, :85:13]
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin
    if (reset)
      head <= 5'h0;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:58:21, :59:21]
    else if (|head)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:59:21, :80:24]
      head <= head + 5'h1;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:59:21, :83:26]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:88];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [6:0] i = 7'h0; i < 7'h59; i += 7'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        head = _RANDOM[7'h58][9:5];	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:59:21]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_deq_vaddr = 40'h0;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:42:14]
  assign io_deq_valid = |head;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:59:21, :80:24]
endmodule

