// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module AtomStridePrefetcher(
  input          clock,
                 reset,
  output [7:0]   io_pat_addr,	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:93:14]
  input  [511:0] io_pat_atom,	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:93:14]
  output [7:0]   io_ast_addr,	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:93:14]
  input          io_ast_status,	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:93:14]
  output         io_amu_lookup_req_valid,	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:93:14]
  input          io_amu_lookup_req_ready,	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:93:14]
  output [39:0]  io_amu_lookup_req_paddr,	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:93:14]
  input          io_amu_lookup_resp_valid,	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:93:14]
  input  [7:0]   io_amu_lookup_resp_atom_id,	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:93:14]
  input          io_amu_lookup_resp_xcpt	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:93:14]
);

  reg  [2:0]  state;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22]
  wire [39:0] _prq_io_deq_paddr;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:133:19]
  wire        _prq_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:133:19]
  reg  [39:0] io_amu_lookup_req_paddr_REG;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:260:38]
  wire        _io_amu_lookup_req_valid_output = state == 3'h1;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22, :261:37]
  reg  [7:0]  io_pat_addr_REG;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:270:38]
  reg  [7:0]  io_ast_addr_REG;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:271:38]
  wire        _pref_addr_T_2 = state == 3'h3;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22, :291:45]
  wire        _GEN = _io_amu_lookup_req_valid_output & io_amu_lookup_req_ready;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:261:37, :349:34]
  wire        _GEN_0 = state == 3'h2;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22, :351:13, :353:20]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:208:13]
    wire _GEN_1 = (|state) & ~_io_amu_lookup_req_valid_output;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22, :217:32, :261:37, :348:3]
    wire _GEN_2 = _GEN_1 & _GEN_0;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:348:3, :353:20, :354:3]
    wire _GEN_3 = _GEN_1 & ~_GEN_0 & _pref_addr_T_2;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:291:45, :348:3, :353:20, :354:3, :363:3]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:208:13]
      if ((`PRINTF_COND_) & 1'h0)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:93:14, :149:42, :208:13, :294:64, :309:40, src/main/scala/chisel3/util/Decoupled.scala:52:35]
        $fwrite(32'h80000002, "Prefetch request buffer is full\n");	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:208:13]
      if ((`PRINTF_COND_) & (|state) & _io_amu_lookup_req_valid_output & _GEN & ~reset)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22, :208:13, :217:32, :261:37, :349:34, :350:13]
        $fwrite(32'h80000002, "---Lookup Fire: 0x%x\n", io_amu_lookup_req_paddr_REG);	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:208:13, :260:38, :350:13]
      if ((`PRINTF_COND_) & _GEN_2 & io_amu_lookup_resp_xcpt & ~reset)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:208:13, :350:13, :354:3, :357:13]
        $fwrite(32'h80000002, "---Lookup Resp XCPT\n");	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:208:13, :357:13]
      if ((`PRINTF_COND_) & _GEN_2 & ~io_amu_lookup_resp_xcpt & io_amu_lookup_resp_valid & ~reset)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:208:13, :350:13, :354:3, :355:34, :359:13]
        $fwrite(32'h80000002, "---Lookup Resp Fire: %d\n", io_amu_lookup_resp_atom_id);	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:208:13, :359:13]
      if ((`PRINTF_COND_) & _GEN_3 & ~reset)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:208:13, :350:13, :363:3, :366:11]
        $fwrite(32'h80000002, "---PAT Access Fire: 0x%x en:%d\n", io_pat_atom[20:0], io_ast_status);	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:208:13, :274:42, :366:11]
      if ((`PRINTF_COND_) & _GEN_3 & io_ast_status & ~reset)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:208:13, :350:13, :363:3, :374:15]
        $fwrite(32'h80000002, "Can initiate prefetch\n");	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:208:13, :374:15]
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin
    if (reset)
      state <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22]
    else if (|state) begin	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22, :217:32]
      if (_io_amu_lookup_req_valid_output) begin	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:261:37]
        if (_GEN)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:349:34]
          state <= 3'h2;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22, :351:13]
      end
      else if (_GEN_0) begin	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:353:20]
        if (io_amu_lookup_resp_xcpt)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:93:14]
          state <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22]
        else if (io_amu_lookup_resp_valid)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:93:14]
          state <= 3'h3;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22, :291:45]
      end
      else if (_pref_addr_T_2)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:291:45]
        state <= {io_ast_status, 2'h0};	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22, :373:38, :375:15, :377:15]
    end
    else if (~(|state) & _prq_io_deq_valid)	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:133:19, :143:22, :217:32, :250:54]
      state <= 3'h1;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22, :261:37]
    io_amu_lookup_req_paddr_REG <= _prq_io_deq_paddr;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:133:19, :260:38]
    io_pat_addr_REG <= io_amu_lookup_resp_atom_id;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:270:38]
    io_ast_addr_REG <= io_amu_lookup_resp_atom_id;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:271:38]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:20];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h15; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        state = _RANDOM[5'hA][6:4];	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22]
        io_amu_lookup_req_paddr_REG = {_RANDOM[5'h12][31:18], _RANDOM[5'h13][25:0]};	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:260:38]
        io_pat_addr_REG = {_RANDOM[5'h13][31:26], _RANDOM[5'h14][1:0]};	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:260:38, :270:38]
        io_ast_addr_REG = _RANDOM[5'h14][9:2];	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:270:38, :271:38]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  RequestQueue prq (	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:133:19]
    .clock        (clock),
    .reset        (reset),
    .io_deq_ready (~(|state)),	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:143:22, :217:32]
    .io_deq_paddr (_prq_io_deq_paddr),
    .io_deq_valid (_prq_io_deq_valid)
  );
  assign io_pat_addr = io_pat_addr_REG;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:270:38]
  assign io_ast_addr = io_ast_addr_REG;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:271:38]
  assign io_amu_lookup_req_valid = _io_amu_lookup_req_valid_output;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:261:37]
  assign io_amu_lookup_req_paddr = io_amu_lookup_req_paddr_REG;	// @[generators/rocket-chip/src/main/scala/tile/AtomPrefetcher.scala:260:38]
endmodule

